package accounting

import "errors"

var (
	ErrInvalidDecimal           = errors.New("accounting: invalid decimal")
	ErrDivisionByZero           = errors.New("accounting: division by zero")
	ErrInvalidArgument          = errors.New("accounting: invalid argument")
	ErrNotFound                 = errors.New("accounting: not found")
	ErrConflict                 = errors.New("accounting: conflict")
	ErrVersionConflict          = errors.New("accounting: version conflict")
	ErrDuplicate                = errors.New("accounting: duplicate")
	ErrIdempotencyConflict      = errors.New("accounting: idempotency conflict")
	ErrUnbalancedEntry          = errors.New("accounting: journal entry is not balanced")
	ErrPeriodClosed             = errors.New("accounting: period is closed")
	ErrPeriodSequence           = errors.New("accounting: period transition is out of sequence")
	ErrPeriodInFuture           = errors.New("accounting: future period cannot be closed")
	ErrFiscalYearOverlap        = errors.New("accounting: fiscal year overlaps another fiscal year")
	ErrFiscalYearSequence       = errors.New("accounting: invalid fiscal year sequence")
	ErrFiscalYearCloseOrder     = errors.New("accounting: fiscal year close is out of order")
	ErrFiscalYearNotReady       = errors.New("accounting: fiscal year is not ready to close")
	ErrFiscalYearReopenOrder    = errors.New("accounting: fiscal year must be reopened in reverse order")
	ErrAnnualClosePending       = errors.New("accounting: annual closing is pending")
	ErrAnnualCloseNotRequired   = errors.New("accounting: annual closing is not required")
	ErrAccountArchived          = errors.New("accounting: account is archived")
	ErrAccountNotPostable       = errors.New("accounting: account is not postable")
	ErrAccountInUse             = errors.New("accounting: account is in use")
	ErrAccountStructureLocked   = errors.New("accounting: account structure is locked")
	ErrInvalidAccountParent     = errors.New("accounting: invalid account parent")
	ErrAccountHierarchyCycle    = errors.New("accounting: account hierarchy contains a cycle")
	ErrMappingIncompatible      = errors.New("accounting: account mapping is incompatible")
	ErrAccountMapped            = errors.New("accounting: account has functional mappings")
	ErrFinancialAccountLinked   = errors.New("accounting: account has a financial dependency")
	ErrAccountHasActiveChildren = errors.New("accounting: account has active children")
	ErrAccountParentInactive    = errors.New("accounting: account parent is inactive")
	ErrAccountProtected         = errors.New("accounting: system account is protected")
	ErrMappingMissing           = errors.New("accounting: account mapping is missing")
	ErrEntryImmutable           = errors.New("accounting: posted journal entry is immutable")
	ErrAlreadyReversed          = errors.New("accounting: journal entry already has a direct reversal")
	ErrReversalNotAllowed       = errors.New("accounting: journal entry cannot be reversed safely")
	ErrReconciliationClosed     = errors.New("accounting: reconciliation is closed")
	ErrInflationIncomplete      = errors.New("accounting: inflation index series is incomplete")
)
