FROM node:20.19.0-alpine

WORKDIR /src

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN chown -R node:node /src

USER node

EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080"]
