/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/organizations/{organizationId}/scheduling/branches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["listSchedulingBranches"];
        put?: never;
        post: operations["createSchedulingBranch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/services": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["listSchedulingServices"];
        put?: never;
        post: operations["createSchedulingService"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/resources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["listSchedulingResources"];
        put?: never;
        post: operations["createSchedulingResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/availability": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["calculateSchedulingAvailability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/availability/rules": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["listSchedulingAvailabilityRules"];
        put?: never;
        post: operations["createSchedulingAvailabilityRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["listSchedulingBlocks"];
        put?: never;
        post: operations["createSchedulingBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/sessions": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSchedulingGroupSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["listSchedulingBookings"];
        put?: never;
        post: operations["createSchedulingBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get: operations["getSchedulingBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/bookings/{bookingId}/reschedule": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rescheduleSchedulingBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/bookings/{bookingId}/{action}": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                bookingId: components["parameters"]["BookingId"];
                action: "confirm" | "cancel" | "check-in" | "complete" | "no-show";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transitionSchedulingBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["listSchedulingWaitlist"];
        put?: never;
        post: operations["createSchedulingWaitlistEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/queue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        get: operations["listSchedulingQueue"];
        put?: never;
        post: operations["createSchedulingQueueTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{organizationId}/scheduling/queue/{ticketId}": {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                ticketId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["advanceSchedulingQueueTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/scheduling/{organizationSlug}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["calculatePublicSchedulingAvailability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/scheduling/{organizationSlug}/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicSchedulingCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/scheduling/{organizationSlug}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPublicSchedulingBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/scheduling/{organizationSlug}/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPublicSchedulingWaitlistEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/scheduling/actions/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["consumePublicSchedulingAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @enum {string} */
            code: "VALIDATION_ERROR" | "NOT_FOUND" | "SLOT_CONFLICT" | "RESOURCE_CONFLICT" | "CAPACITY_EXCEEDED" | "BOOKING_VERSION_CONFLICT" | "HOLD_EXPIRED" | "ACTION_TOKEN_INVALID" | "ACTION_TOKEN_EXPIRED" | "BOOKING_STATE_INVALID" | "IDEMPOTENCY_KEY_REUSED" | "FORBIDDEN";
            message?: string;
        };
        Allocation: {
            /** Format: uuid */
            resource_id: string;
            /** @enum {string} */
            mode: "capacity" | "exclusive";
            units: number;
        };
        BranchInput: {
            /** Format: uuid */
            id?: string;
            code: string;
            slug?: string;
            name: string;
            /** @description Zona IANA */
            timezone: string;
            address?: string;
            /** @default true */
            active: boolean;
        };
        Branch: components["schemas"]["BranchInput"] & {
            /** Format: uuid */
            id: string;
            organization_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ResourceRequirement: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            resource_id?: string;
            resource_kind: components["schemas"]["ResourceKind"];
            /** @enum {string} */
            allocation_mode: "capacity" | "exclusive";
            units: number;
            /** @default false */
            optional: boolean;
        };
        ServiceInput: {
            /** Format: uuid */
            id?: string;
            code: string;
            name: string;
            description?: string;
            duration_minutes: number;
            buffer_before_minutes?: number;
            buffer_after_minutes?: number;
            slot_minutes: number;
            price: string;
            currency: string;
            /** @enum {string} */
            fulfillment_mode: "in_person" | "virtual" | "hybrid";
            max_participants: number;
            allow_group?: boolean;
            allow_waitlist?: boolean;
            confirmation_required?: boolean;
            /** @default true */
            active: boolean;
            resource_requirements?: components["schemas"]["ResourceRequirement"][];
        };
        Service: components["schemas"]["ServiceInput"] & {
            /** Format: uuid */
            id: string;
            organization_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        ResourceKind: "professional" | "room" | "machine" | "vehicle" | "equipment" | "generic";
        ResourceInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            branch_id: string;
            code: string;
            name: string;
            kind: components["schemas"]["ResourceKind"];
            capacity: number;
            /** @description Zona IANA */
            timezone: string;
            /** @default true */
            active: boolean;
        };
        Resource: components["schemas"]["ResourceInput"] & {
            /** Format: uuid */
            id: string;
            organization_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AvailabilityRuleInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            resource_id?: string;
            /** @enum {string} */
            kind: "branch" | "resource";
            weekday: number;
            start_minute: number;
            end_minute: number;
            /** Format: date-time */
            valid_from?: string;
            /** Format: date-time */
            valid_until?: string;
            timezone: string;
            /** @default true */
            active: boolean;
        };
        AvailabilityRule: components["schemas"]["AvailabilityRuleInput"] & {
            /** Format: uuid */
            id: string;
            organization_id: string;
        };
        AvailabilityExceptionInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            resource_id?: string;
            /** @enum {string} */
            kind: "holiday" | "vacation" | "absence" | "manual" | "maintenance" | "availability";
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            reason?: string;
        };
        AvailabilityException: components["schemas"]["AvailabilityExceptionInput"] & {
            /** Format: uuid */
            id: string;
            organization_id: string;
        };
        AvailabilityQuery: {
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            service_id: string;
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            until: string;
            participants: number;
            /** @description Recursos elegidos. Puede omitirse para que Pymes devuelva combinaciones elegibles, incluido cualquier profesional. */
            allocations?: components["schemas"]["Allocation"][];
        };
        PublicSchedulingCatalog: {
            branches: components["schemas"]["PublicSchedulingBranch"][];
            services: components["schemas"]["PublicSchedulingService"][];
            resources: components["schemas"]["PublicSchedulingResource"][];
        };
        PublicSchedulingBranch: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            timezone: string;
            address: string;
        };
        PublicSchedulingService: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            description: string;
            duration_minutes: number;
            buffer_before_minutes: number;
            buffer_after_minutes: number;
            slot_minutes: number;
            price: string;
            currency: string;
            /** @enum {string} */
            fulfillment_mode: "in_person" | "virtual" | "hybrid";
            max_participants: number;
            allow_group: boolean;
            allow_waitlist: boolean;
            confirmation_required: boolean;
        };
        PublicSchedulingResource: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            branch_id: string;
            name: string;
            /** @enum {string} */
            kind: "professional" | "room" | "machine" | "vehicle" | "equipment" | "generic";
            capacity: number;
            timezone: string;
        };
        Slot: {
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            /** Format: date-time */
            occupies_from: string;
            /** Format: date-time */
            occupies_until: string;
            timezone: string;
            allocations: components["schemas"]["Allocation"][];
            remaining: number;
        };
        Customer: {
            party_id?: string;
            name: string;
            /** Format: email */
            email?: string;
            phone?: string;
        };
        Recurrence: {
            /** @enum {string} */
            frequency: "daily" | "weekly";
            interval: number;
            count?: number;
            /** Format: date-time */
            until?: string;
            by_weekdays?: number[];
        };
        BookingInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            service_id: string;
            /** Format: uuid */
            session_id?: string;
            customer: components["schemas"]["Customer"];
            /** Format: date-time */
            start_at: string;
            participants: number;
            /** @enum {string} */
            status?: "held" | "pending_confirmation" | "confirmed";
            hold_minutes?: number;
            allocations?: components["schemas"]["Allocation"][];
            notes?: string;
            recurrence?: components["schemas"]["Recurrence"];
        };
        Booking: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            series_id?: string;
            /** Format: uuid */
            session_id?: string;
            /** Format: uuid */
            supersedes_id?: string;
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            service_id: string;
            party_id: string;
            /** @enum {string} */
            status: "held" | "pending_confirmation" | "confirmed" | "checked_in" | "completed" | "cancelled" | "rescheduled" | "no_show";
            participants: number;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            version: number;
            service_name: string;
            price: string;
            currency: string;
            duration_minutes: number;
            timezone: string;
            customer_name?: string;
            /** Format: email */
            customer_email?: string;
            customer_phone?: string;
            notes?: string;
            cancellation_reason?: string;
            allocations: components["schemas"]["Allocation"][];
        };
        PublicBooking: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            series_id?: string;
            /** Format: uuid */
            session_id?: string;
            /** Format: uuid */
            supersedes_id?: string;
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            service_id: string;
            /** @enum {string} */
            status: "held" | "pending_confirmation" | "confirmed" | "checked_in" | "completed" | "cancelled" | "rescheduled" | "no_show";
            participants: number;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            version: number;
            service_name: string;
            price: string;
            currency: string;
            duration_minutes: number;
            timezone: string;
        };
        GroupSessionInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            service_id: string;
            /** Format: date-time */
            start_at: string;
            capacity: number;
            allocations: components["schemas"]["Allocation"][];
        };
        GroupSession: components["schemas"]["GroupSessionInput"] & {
            /** Format: uuid */
            id: string;
            booked: number;
            version: number;
            /** @enum {string} */
            status: "open" | "closed" | "cancelled" | "completed";
        };
        RescheduleInput: {
            expected_version: number;
            /** Format: date-time */
            start_at: string;
            /** @description Duración snapshot nueva para resize; omitida conserva la actual. */
            duration_minutes?: number;
            allocations?: components["schemas"]["Allocation"][];
        };
        TransitionInput: {
            expected_version: number;
            reason?: string;
        };
        WaitlistInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            service_id: string;
            customer: components["schemas"]["Customer"];
            /** Format: date-time */
            preferred_from: string;
            /** Format: date-time */
            preferred_until: string;
            participants: number;
        };
        WaitlistEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            service_id: string;
            party_id: string;
            customer_name?: string;
            /** Format: email */
            customer_email?: string;
            customer_phone?: string;
            /** Format: date-time */
            preferred_from: string;
            /** Format: date-time */
            preferred_until: string;
            participants: number;
            /** @enum {string} */
            status: "pending" | "offered" | "accepted" | "cancelled" | "expired";
            /** Format: date-time */
            offer_expires_at?: string;
            /** Format: date-time */
            offered_start_at?: string;
            /** Format: date-time */
            offered_end_at?: string;
            offered_allocations?: components["schemas"]["Allocation"][];
            /** Format: uuid */
            accepted_booking_id?: string;
            version: number;
        };
        PublicWaitlistEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            service_id: string;
            /** Format: date-time */
            preferred_from: string;
            /** Format: date-time */
            preferred_until: string;
            participants: number;
            /** @enum {string} */
            status: "pending" | "offered" | "accepted" | "cancelled" | "expired";
            /** Format: date-time */
            offer_expires_at?: string;
            /** Format: date-time */
            offered_start_at?: string;
            /** Format: date-time */
            offered_end_at?: string;
            offered_allocations?: components["schemas"]["Allocation"][];
            /** Format: uuid */
            accepted_booking_id?: string;
            version: number;
        };
        QueueTicketInput: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            branch_id: string;
            /** Format: uuid */
            service_id: string;
            party_id: string;
            priority?: number;
        };
        QueueTicket: components["schemas"]["QueueTicketInput"] & {
            /** Format: uuid */
            id: string;
            number: number;
            /** @enum {string} */
            status: "waiting" | "called" | "serving" | "completed" | "no_show" | "cancelled";
            version: number;
        };
        QueueAdvanceInput: {
            expected_version: number;
            /** @enum {string} */
            status: "called" | "serving" | "completed" | "no_show" | "cancelled";
        };
        PublicActionInput: {
            /** @enum {string} */
            purpose: "confirm" | "cancel" | "reschedule" | "accept_waitlist";
            expected_version: number;
            /** Format: date-time */
            start_at?: string;
            duration_minutes?: number;
            reason?: string;
        };
    };
    responses: {
        /** @description Falta membresía activa, tenant listo o permiso scheduling. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error estable del dominio de Agenda. */
        SchedulingError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        OrganizationId: string;
        OrganizationSlug: string;
        BookingId: string;
        IdempotencyKey: string;
        SourceVersion: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSchedulingBranches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sucursales */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createSchedulingBranch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchInput"];
            };
        };
        responses: {
            /** @description Sucursal creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SchedulingError"];
        };
    };
    listSchedulingServices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servicios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createSchedulingService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceInput"];
            };
        };
        responses: {
            /** @description Servicio creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SchedulingError"];
        };
    };
    listSchedulingResources: {
        parameters: {
            query?: {
                branch_id?: string;
            };
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recursos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createSchedulingResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceInput"];
            };
        };
        responses: {
            /** @description Recurso creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SchedulingError"];
        };
    };
    calculateSchedulingAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityQuery"];
            };
        };
        responses: {
            /** @description Slots revalidables */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
        };
    };
    listSchedulingAvailabilityRules: {
        parameters: {
            query: {
                branch_id: string;
            };
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reglas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRule"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createSchedulingAvailabilityRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityRuleInput"];
            };
        };
        responses: {
            /** @description Regla creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRule"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
        };
    };
    listSchedulingBlocks: {
        parameters: {
            query: {
                branch_id: string;
                from: string;
                until: string;
            };
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bloqueos y excepciones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityException"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createSchedulingBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityExceptionInput"];
            };
        };
        responses: {
            /** @description Bloqueo creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityException"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
        };
    };
    createSchedulingGroupSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupSessionInput"];
            };
        };
        responses: {
            /** @description Sesión grupal creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupSession"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SchedulingError"];
        };
    };
    listSchedulingBookings: {
        parameters: {
            query: {
                branch_id: string;
                from: string;
                until: string;
            };
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Turnos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createSchedulingBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingInput"];
            };
        };
        responses: {
            /** @description Turno o serie creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SchedulingError"];
        };
    };
    getSchedulingBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Turno */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["SchedulingError"];
        };
    };
    rescheduleSchedulingBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                bookingId: components["parameters"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RescheduleInput"];
            };
        };
        responses: {
            /** @description Turno reemplazante */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SchedulingError"];
        };
    };
    transitionSchedulingBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                bookingId: components["parameters"]["BookingId"];
                action: "confirm" | "cancel" | "check-in" | "complete" | "no-show";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionInput"];
            };
        };
        responses: {
            /** @description Turno actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SchedulingError"];
        };
    };
    listSchedulingWaitlist: {
        parameters: {
            query: {
                branch_id: string;
            };
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de espera */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistEntry"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createSchedulingWaitlistEntry: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistInput"];
            };
        };
        responses: {
            /** @description Entrada creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistEntry"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SchedulingError"];
        };
    };
    listSchedulingQueue: {
        parameters: {
            query: {
                branch_id: string;
            };
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cola */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueTicket"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    createSchedulingQueueTicket: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueTicketInput"];
            };
        };
        responses: {
            /** @description Ticket creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueTicket"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
        };
    };
    advanceSchedulingQueueTicket: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueAdvanceInput"];
            };
        };
        responses: {
            /** @description Ticket actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueTicket"];
                };
            };
            400: components["responses"]["SchedulingError"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SchedulingError"];
        };
    };
    calculatePublicSchedulingAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationSlug: components["parameters"]["OrganizationSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityQuery"];
            };
        };
        responses: {
            /** @description Slots públicos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            400: components["responses"]["SchedulingError"];
            404: components["responses"]["SchedulingError"];
        };
    };
    getPublicSchedulingCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationSlug: components["parameters"]["OrganizationSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catálogo público activo sin PII */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSchedulingCatalog"];
                };
            };
            404: components["responses"]["SchedulingError"];
        };
    };
    createPublicSchedulingBooking: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationSlug: components["parameters"]["OrganizationSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingInput"];
            };
        };
        responses: {
            /** @description Turno público creado sin datos internos del cliente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBooking"][];
                };
            };
            400: components["responses"]["SchedulingError"];
            404: components["responses"]["SchedulingError"];
            409: components["responses"]["SchedulingError"];
        };
    };
    createPublicSchedulingWaitlistEntry: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                organizationSlug: components["parameters"]["OrganizationSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistInput"];
            };
        };
        responses: {
            /** @description Entrada pública creada sin datos internos del cliente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicWaitlistEntry"];
                };
            };
            400: components["responses"]["SchedulingError"];
            404: components["responses"]["SchedulingError"];
        };
    };
    consumePublicSchedulingAction: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Source-Version"?: components["parameters"]["SourceVersion"];
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicActionInput"];
            };
        };
        responses: {
            /** @description Acción consumida idempotentemente sin exponer datos internos del cliente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBooking"] | components["schemas"]["PublicWaitlistEntry"];
                };
            };
            400: components["responses"]["SchedulingError"];
            401: components["responses"]["SchedulingError"];
            409: components["responses"]["SchedulingError"];
            410: components["responses"]["SchedulingError"];
        };
    };
}
