DROP TABLE IF EXISTS admin_activity_events;
DROP TABLE IF EXISTS tenant_usage_counters;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS tenant_api_key_scopes;
DROP TABLE IF EXISTS tenant_api_keys;
DROP TABLE IF EXISTS tenant_settings;
DROP TABLE IF EXISTS tenant_memberships;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tenants;
