//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AssignableRole.
const (
	AssignableRoleAdmin  AssignableRole = "admin"
	AssignableRoleMember AssignableRole = "member"
)

// Valid indicates whether the value is a known member of the AssignableRole enum.
func (e AssignableRole) Valid() bool {
	switch e {
	case AssignableRoleAdmin:
		return true
	case AssignableRoleMember:
		return true
	default:
		return false
	}
}

// Defines values for InvitationStatus.
const (
	InvitationStatusAccepted InvitationStatus = "accepted"
	InvitationStatusExpired  InvitationStatus = "expired"
	InvitationStatusPending  InvitationStatus = "pending"
	InvitationStatusRevoked  InvitationStatus = "revoked"
)

// Valid indicates whether the value is a known member of the InvitationStatus enum.
func (e InvitationStatus) Valid() bool {
	switch e {
	case InvitationStatusAccepted:
		return true
	case InvitationStatusExpired:
		return true
	case InvitationStatusPending:
		return true
	case InvitationStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for MembershipStatus.
const (
	MembershipStatusActive      MembershipStatus = "active"
	MembershipStatusPending     MembershipStatus = "pending"
	MembershipStatusQuarantined MembershipStatus = "quarantined"
	MembershipStatusRemoved     MembershipStatus = "removed"
)

// Valid indicates whether the value is a known member of the MembershipStatus enum.
func (e MembershipStatus) Valid() bool {
	switch e {
	case MembershipStatusActive:
		return true
	case MembershipStatusPending:
		return true
	case MembershipStatusQuarantined:
		return true
	case MembershipStatusRemoved:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationStatus.
const (
	OrganizationStatusActive       OrganizationStatus = "active"
	OrganizationStatusDisabled     OrganizationStatus = "disabled"
	OrganizationStatusProvisioning OrganizationStatus = "provisioning"
	OrganizationStatusSuspended    OrganizationStatus = "suspended"
)

// Valid indicates whether the value is a known member of the OrganizationStatus enum.
func (e OrganizationStatus) Valid() bool {
	switch e {
	case OrganizationStatusActive:
		return true
	case OrganizationStatusDisabled:
		return true
	case OrganizationStatusProvisioning:
		return true
	case OrganizationStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for Permission.
const (
	OrganizationUpdate    Permission = "organization:update"
	OrganizationView      Permission = "organization:view"
	SessionsManageSelf    Permission = "sessions:manage:self"
	TeamInvitationCreate  Permission = "team:invitation:create"
	TeamInvitationManage  Permission = "team:invitation:manage"
	TeamMemberRemove      Permission = "team:member:remove"
	TeamMemberUpdate      Permission = "team:member:update"
	TeamOwnershipTransfer Permission = "team:ownership:transfer"
	TeamView              Permission = "team:view"
)

// Valid indicates whether the value is a known member of the Permission enum.
func (e Permission) Valid() bool {
	switch e {
	case OrganizationUpdate:
		return true
	case OrganizationView:
		return true
	case SessionsManageSelf:
		return true
	case TeamInvitationCreate:
		return true
	case TeamInvitationManage:
		return true
	case TeamMemberRemove:
		return true
	case TeamMemberUpdate:
		return true
	case TeamOwnershipTransfer:
		return true
	case TeamView:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin  Role = "admin"
	RoleMember Role = "member"
	RoleOwner  Role = "owner"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleMember:
		return true
	case RoleOwner:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeConfigAuthProvider.
const (
	Clerk RuntimeConfigAuthProvider = "clerk"
)

// Valid indicates whether the value is a known member of the RuntimeConfigAuthProvider enum.
func (e RuntimeConfigAuthProvider) Valid() bool {
	switch e {
	case Clerk:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	SessionStatusAbandoned SessionStatus = "abandoned"
	SessionStatusActive    SessionStatus = "active"
	SessionStatusEnded     SessionStatus = "ended"
	SessionStatusExpired   SessionStatus = "expired"
	SessionStatusPending   SessionStatus = "pending"
	SessionStatusRemoved   SessionStatus = "removed"
	SessionStatusReplaced  SessionStatus = "replaced"
	SessionStatusRevoked   SessionStatus = "revoked"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusAbandoned:
		return true
	case SessionStatusActive:
		return true
	case SessionStatusEnded:
		return true
	case SessionStatusExpired:
		return true
	case SessionStatusPending:
		return true
	case SessionStatusRemoved:
		return true
	case SessionStatusReplaced:
		return true
	case SessionStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for SyncStatus.
const (
	SyncStatusFailed  SyncStatus = "failed"
	SyncStatusPending SyncStatus = "pending"
	SyncStatusQueued  SyncStatus = "queued"
	SyncStatusSynced  SyncStatus = "synced"
)

// Valid indicates whether the value is a known member of the SyncStatus enum.
func (e SyncStatus) Valid() bool {
	switch e {
	case SyncStatusFailed:
		return true
	case SyncStatusPending:
		return true
	case SyncStatusQueued:
		return true
	case SyncStatusSynced:
		return true
	default:
		return false
	}
}

// AssignableRole Roles administrables mediante invitación o edición. `owner` sólo se obtiene con el comando atómico de transferencia de propiedad.
type AssignableRole string

// CreateInvitationInput defines model for CreateInvitationInput.
type CreateInvitationInput struct {
	Email openapi_types.Email `json:"email"`

	// Role Roles administrables mediante invitación o edición. `owner` sólo se obtiene con el comando atómico de transferencia de propiedad.
	Role AssignableRole `json:"role"`
}

// CurrentSession defines model for CurrentSession.
type CurrentSession struct {
	Membership   Membership   `json:"membership"`
	Organization Organization `json:"organization"`
	Permissions  []Permission `json:"permissions"`

	// Role Rol efectivo después de intersectar el rol local con el rol grueso de Clerk.
	Role      Role   `json:"role"`
	SessionId string `json:"session_id"`
	User      User   `json:"user"`
}

// DeviceSession defines model for DeviceSession.
type DeviceSession struct {
	CreatedAt    time.Time `json:"created_at"`
	Current      bool      `json:"current"`
	ExpiresAt    time.Time `json:"expires_at"`
	Id           string    `json:"id"`
	LastActiveAt time.Time `json:"last_active_at"`

	// Status Estado normalizado de la sesión informado por Clerk.
	Status SessionStatus `json:"status"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code Código estable. IAM usa `AUTH_INVALID_TOKEN`, `AUTH_ORGANIZATION_REQUIRED`, `IAM_MEMBERSHIP_REQUIRED`, `IAM_FORBIDDEN`, `IAM_ROLE_CONFLICT`, `IAM_INVITATION_PENDING`, `AUTH_PROVIDER_RATE_LIMITED`, `AUTH_NOT_CONFIGURED`, `AUTH_PROVIDER_UNAVAILABLE`, `IAM_UNAVAILABLE`, `REQUEST_INVALID`, `IDEMPOTENCY_KEY_CONFLICT`, `IDEMPOTENCY_IN_PROGRESS`, `WEBHOOK_INVALID_PAYLOAD` y `WEBHOOK_INVALID_SIGNATURE`.
		Code      string                  `json:"code"`
		Details   *map[string]interface{} `json:"details,omitempty"`
		Message   string                  `json:"message"`
		RequestId *string                 `json:"request_id,omitempty"`
	} `json:"error"`
}

// Invitation defines model for Invitation.
type Invitation struct {
	Email     openapi_types.Email `json:"email"`
	ExpiresAt time.Time           `json:"expires_at"`
	Id        openapi_types.UUID  `json:"id"`
	Role      Role                `json:"role"`

	// Status Ciclo de vida local; el estado de sincronización se expone por separado.
	Status     InvitationStatus `json:"status"`
	SyncStatus SyncStatus       `json:"sync_status"`
}

// InvitationList defines model for InvitationList.
type InvitationList struct {
	Items []Invitation `json:"items"`
	Page  PageInfo     `json:"page"`
}

// InvitationStatus Ciclo de vida local; el estado de sincronización se expone por separado.
type InvitationStatus string

// Member defines model for Member.
type Member struct {
	Id         openapi_types.UUID `json:"id"`
	Role       Role               `json:"role"`
	Status     MembershipStatus   `json:"status"`
	SyncStatus SyncStatus         `json:"sync_status"`
	User       User               `json:"user"`
}

// MemberList defines model for MemberList.
type MemberList struct {
	Items []Member `json:"items"`
	Page  PageInfo `json:"page"`
}

// Membership defines model for Membership.
type Membership struct {
	Id openapi_types.UUID `json:"id"`

	// Role Rol local autoritativo almacenado en PostgreSQL.
	Role   Role             `json:"role"`
	Status MembershipStatus `json:"status"`
}

// MembershipStatus defines model for MembershipStatus.
type MembershipStatus string

// Organization defines model for Organization.
type Organization struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`

	// Role Rol local de la membresía del usuario en esta organización.
	Role   Role               `json:"role"`
	Slug   string             `json:"slug"`
	Status OrganizationStatus `json:"status"`

	// SwitchKey Referencia opaca usada únicamente con Clerk.setActive().
	SwitchKey  *string    `json:"switch_key,omitempty"`
	SyncStatus SyncStatus `json:"sync_status"`
}

// OrganizationList defines model for OrganizationList.
type OrganizationList struct {
	Items []Organization `json:"items"`
	Page  PageInfo       `json:"page"`
}

// OrganizationStatus defines model for OrganizationStatus.
type OrganizationStatus string

// PageInfo defines model for PageInfo.
type PageInfo struct {
	NextCursor *string `json:"next_cursor,omitempty"`
	Total      int     `json:"total"`
}

// Permission Permiso IAM efectivo derivado del rol efectivo.
type Permission string

// Role defines model for Role.
type Role string

// RuntimeConfig defines model for RuntimeConfig.
type RuntimeConfig struct {
	Auth struct {
		Configured bool                      `json:"configured"`
		Provider   RuntimeConfigAuthProvider `json:"provider"`

		// PublishableKey Presente si y sólo si `configured` es true.
		PublishableKey *string `json:"publishable_key,omitempty"`
	} `json:"auth"`
}

// RuntimeConfigAuthProvider defines model for RuntimeConfig.Auth.Provider.
type RuntimeConfigAuthProvider string

// SessionList defines model for SessionList.
type SessionList struct {
	Items []DeviceSession `json:"items"`
	Page  PageInfo        `json:"page"`
}

// SessionStatus Estado normalizado de la sesión informado por Clerk.
type SessionStatus string

// SyncStatus defines model for SyncStatus.
type SyncStatus string

// TransferOwnershipInput defines model for TransferOwnershipInput.
type TransferOwnershipInput struct {
	MemberId openapi_types.UUID `json:"member_id"`
}

// UpdateMemberInput defines model for UpdateMemberInput.
type UpdateMemberInput struct {
	// Role Roles administrables mediante invitación o edición. `owner` sólo se obtiene con el comando atómico de transferencia de propiedad.
	Role AssignableRole `json:"role"`
}

// UpdateOrganizationInput defines model for UpdateOrganizationInput.
type UpdateOrganizationInput struct {
	Name string `json:"name"`
}

// User defines model for User.
type User struct {
	AvatarUrl   *string             `json:"avatar_url,omitempty"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
}

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// InvitationID defines model for InvitationID.
type InvitationID = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// MemberID defines model for MemberID.
type MemberID = openapi_types.UUID

// SessionID defines model for SessionID.
type SessionID = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// RateLimited defines model for RateLimited.
type RateLimited = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// Unavailable defines model for Unavailable.
type Unavailable = ErrorResponse

// WebhookBadRequest defines model for WebhookBadRequest.
type WebhookBadRequest = ErrorResponse

// WebhookUnauthorized defines model for WebhookUnauthorized.
type WebhookUnauthorized = ErrorResponse

// WebhookUnavailable defines model for WebhookUnavailable.
type WebhookUnavailable = ErrorResponse

// UpdateCurrentOrganizationParams defines parameters for UpdateCurrentOrganization.
type UpdateCurrentOrganizationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListMyOrganizationsParams defines parameters for ListMyOrganizations.
type ListMyOrganizationsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListMySessionsParams defines parameters for ListMySessions.
type ListMySessionsParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// RevokeMySessionParams defines parameters for RevokeMySession.
type RevokeMySessionParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListTeamInvitationsParams defines parameters for ListTeamInvitations.
type ListTeamInvitationsParams struct {
	Cursor *Cursor           `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit            `form:"limit,omitempty" json:"limit,omitempty"`
	Status *InvitationStatus `form:"status,omitempty" json:"status,omitempty"`
}

// CreateTeamInvitationParams defines parameters for CreateTeamInvitation.
type CreateTeamInvitationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ResendTeamInvitationParams defines parameters for ResendTeamInvitation.
type ResendTeamInvitationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// RevokeTeamInvitationParams defines parameters for RevokeTeamInvitation.
type RevokeTeamInvitationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListTeamMembersParams defines parameters for ListTeamMembers.
type ListTeamMembersParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// RemoveTeamMemberParams defines parameters for RemoveTeamMember.
type RemoveTeamMemberParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// UpdateTeamMemberParams defines parameters for UpdateTeamMember.
type UpdateTeamMemberParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// TransferOwnershipParams defines parameters for TransferOwnership.
type TransferOwnershipParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ReceiveClerkWebhookJSONBody defines parameters for ReceiveClerkWebhook.
type ReceiveClerkWebhookJSONBody map[string]interface{}

// UpdateCurrentOrganizationJSONRequestBody defines body for UpdateCurrentOrganization for application/json ContentType.
type UpdateCurrentOrganizationJSONRequestBody = UpdateOrganizationInput

// CreateTeamInvitationJSONRequestBody defines body for CreateTeamInvitation for application/json ContentType.
type CreateTeamInvitationJSONRequestBody = CreateInvitationInput

// UpdateTeamMemberJSONRequestBody defines body for UpdateTeamMember for application/json ContentType.
type UpdateTeamMemberJSONRequestBody = UpdateMemberInput

// TransferOwnershipJSONRequestBody defines body for TransferOwnership for application/json ContentType.
type TransferOwnershipJSONRequestBody = TransferOwnershipInput

// ReceiveClerkWebhookJSONRequestBody defines body for ReceiveClerkWebhook for application/json ContentType.
type ReceiveClerkWebhookJSONRequestBody ReceiveClerkWebhookJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (PATCH /api/v1/organization)
	UpdateCurrentOrganization(w http.ResponseWriter, r *http.Request, params UpdateCurrentOrganizationParams)

	// (GET /api/v1/organizations)
	ListMyOrganizations(w http.ResponseWriter, r *http.Request, params ListMyOrganizationsParams)

	// (GET /api/v1/runtime-config)
	GetRuntimeConfig(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/session)
	GetCurrentSession(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/sessions)
	ListMySessions(w http.ResponseWriter, r *http.Request, params ListMySessionsParams)

	// (DELETE /api/v1/sessions/{session_id})
	RevokeMySession(w http.ResponseWriter, r *http.Request, sessionId SessionID, params RevokeMySessionParams)

	// (GET /api/v1/team/invitations)
	ListTeamInvitations(w http.ResponseWriter, r *http.Request, params ListTeamInvitationsParams)

	// (POST /api/v1/team/invitations)
	CreateTeamInvitation(w http.ResponseWriter, r *http.Request, params CreateTeamInvitationParams)

	// (POST /api/v1/team/invitations/{invitation_id}/resend)
	ResendTeamInvitation(w http.ResponseWriter, r *http.Request, invitationId InvitationID, params ResendTeamInvitationParams)

	// (POST /api/v1/team/invitations/{invitation_id}/revoke)
	RevokeTeamInvitation(w http.ResponseWriter, r *http.Request, invitationId InvitationID, params RevokeTeamInvitationParams)

	// (GET /api/v1/team/members)
	ListTeamMembers(w http.ResponseWriter, r *http.Request, params ListTeamMembersParams)

	// (DELETE /api/v1/team/members/{member_id})
	RemoveTeamMember(w http.ResponseWriter, r *http.Request, memberId MemberID, params RemoveTeamMemberParams)

	// (PATCH /api/v1/team/members/{member_id})
	UpdateTeamMember(w http.ResponseWriter, r *http.Request, memberId MemberID, params UpdateTeamMemberParams)

	// (POST /api/v1/team/ownership-transfer)
	TransferOwnership(w http.ResponseWriter, r *http.Request, params TransferOwnershipParams)

	// (POST /webhooks/clerk)
	ReceiveClerkWebhook(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UpdateCurrentOrganization operation middleware
func (siw *ServerInterfaceWrapper) UpdateCurrentOrganization(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateCurrentOrganizationParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCurrentOrganization(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMyOrganizations operation middleware
func (siw *ServerInterfaceWrapper) ListMyOrganizations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMyOrganizationsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMyOrganizations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRuntimeConfig operation middleware
func (siw *ServerInterfaceWrapper) GetRuntimeConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRuntimeConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMySessions operation middleware
func (siw *ServerInterfaceWrapper) ListMySessions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMySessionsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMySessions(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeMySession operation middleware
func (siw *ServerInterfaceWrapper) RevokeMySession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "session_id" -------------
	var sessionId SessionID

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", r.PathValue("session_id"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RevokeMySessionParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeMySession(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTeamInvitations operation middleware
func (siw *ServerInterfaceWrapper) ListTeamInvitations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTeamInvitationsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTeamInvitations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTeamInvitation operation middleware
func (siw *ServerInterfaceWrapper) CreateTeamInvitation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTeamInvitationParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTeamInvitation(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResendTeamInvitation operation middleware
func (siw *ServerInterfaceWrapper) ResendTeamInvitation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "invitation_id" -------------
	var invitationId InvitationID

	err = runtime.BindStyledParameterWithOptions("simple", "invitation_id", r.PathValue("invitation_id"), &invitationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invitation_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResendTeamInvitationParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResendTeamInvitation(w, r, invitationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeTeamInvitation operation middleware
func (siw *ServerInterfaceWrapper) RevokeTeamInvitation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "invitation_id" -------------
	var invitationId InvitationID

	err = runtime.BindStyledParameterWithOptions("simple", "invitation_id", r.PathValue("invitation_id"), &invitationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invitation_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RevokeTeamInvitationParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeTeamInvitation(w, r, invitationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTeamMembers operation middleware
func (siw *ServerInterfaceWrapper) ListTeamMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTeamMembersParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTeamMembers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveTeamMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveTeamMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "member_id" -------------
	var memberId MemberID

	err = runtime.BindStyledParameterWithOptions("simple", "member_id", r.PathValue("member_id"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RemoveTeamMemberParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveTeamMember(w, r, memberId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTeamMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateTeamMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "member_id" -------------
	var memberId MemberID

	err = runtime.BindStyledParameterWithOptions("simple", "member_id", r.PathValue("member_id"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "member_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateTeamMemberParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTeamMember(w, r, memberId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TransferOwnership operation middleware
func (siw *ServerInterfaceWrapper) TransferOwnership(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params TransferOwnershipParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TransferOwnership(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReceiveClerkWebhook operation middleware
func (siw *ServerInterfaceWrapper) ReceiveClerkWebhook(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReceiveClerkWebhook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/runtime-config", wrapper.GetRuntimeConfig)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/session", wrapper.GetCurrentSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/organizations", wrapper.ListMyOrganizations)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/organization", wrapper.UpdateCurrentOrganization)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/sessions", wrapper.ListMySessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/sessions/{session_id}", wrapper.RevokeMySession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/team/members", wrapper.ListTeamMembers)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/api/v1/team/members/{member_id}", wrapper.RemoveTeamMember)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/v1/team/members/{member_id}", wrapper.UpdateTeamMember)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/team/ownership-transfer", wrapper.TransferOwnership)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/team/invitations", wrapper.ListTeamInvitations)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/team/invitations", wrapper.CreateTeamInvitation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/team/invitations/{invitation_id}/resend", wrapper.ResendTeamInvitation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/v1/team/invitations/{invitation_id}/revoke", wrapper.RevokeTeamInvitation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/webhooks/clerk", wrapper.ReceiveClerkWebhook)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FxLcxs5kv4riNo5dG+URdndHbHDPtEW7eZaEjUU1R09Di0FViUpjKuAMoAqi+3gj9njHObk21z1xzaQ",
	"qAfqQVJve2Z9cVj1ABLILxNfPlifvEDEieDAtfL6n7yEShqDBol/vUqlEtL8j3Gv731IQa483+M0Bq/v",
	"Bfau76ngEmJqHovp1SHwpb70+j89f+F7epWYJ5WWjC+99dr3RiHEidDAg9VbWJVDXwINQVZjO489M8/5",
	"noQPKZMQen0tU9gw6YuffvK9mPHi7//qFIFnTFPNBB8dlAIkVF9W07PykRkLt06+EDKm2ut7aYpPtqc7",
	"ZDHTm/YwwpvugCEsaBppsxbfLI3Faez1n+/v48Lyv8p5GNewBIkTHUE8B7lxTTHevv96TkGpbXun7P1d",
	"E23R2vP2tGszlEoEV4DIfEnDCXxIQeHOBoJr4PhfmiQRC1B1vb8pwc21atI/SVh4fe8/ehXqe/au6g2l",
	"FHKST2KnDEEFkiVmMK/v5RMSxrPr/41YKMh3F5PhX86Gp9PZ6PjXweHo4OL7PW/te68EX0QseELZihkF",
	"CQQnEBFQmoaC0ECnNCLfXYwGR7PJ+HA4ezU+fn04ejW98AleHB3/OpoOpqPx8exkeHwwOn6Ddw6GRyfj",
	"6fD41e+zt8Pfq7eIqN8cHc9OJuM3k+Hpab7410LOWRgCf7rVj0LgmoU0JFYzlCjGCQ0CUIKodMECBlwD",
	"+e5icDb9ZTaevBkcj/5qF200OJoMD4r9OBoevRxOTn8ZnVS3cNGDo9nr8eTl6OBgeJwvdUI1oHkbgD+Z",
	"qiOQ7wk6juvPRBs/KWkU4wIjSkQCkgbs+jMvlnsyGf86OhhOZpPBdDg7HB2NpkNEqp+7XbSoCWi5ejZY",
	"aJB1YVumuPa9M05TfSkk++NJVy4hBB4wGhGaKlywKK2RFsvNTXE2Hb8tFXXGaUZZROcRPJ24g9RMwoJc",
	"Gxxtc8GWqaSVtMfjKRrX6M2ZQdr3RJBEigwgFLKhXMZDZmZj8whauj07Hvw6GB0OXh4OL77fI2eckgWN",
	"IlqOQUKEB021kGgqo8ERiURAI5IqavHtDoL79hvML4V4/yW87QldRYKGRuyPVoqa4/1t+PKX8fhtqe2T",
	"we+H40HhgHO5vwxMXzMZU4Jm2jvN2NUGsDZXcDp6czyYnk2GrTU8PXRPIZCghbv5NfiKLfBlfC6uEF1b",
	"4dvEm1n0uiAI6JEGSrElNwufCLv4xnksIlCEhoYWKS3Ng4rEEDJqpzMUzpqeIBAy/O8euRAfOcgLoq4/",
	"R4IoIGKuGXAoDs5AxJSbk1Nff45ZgHugJeVqARKdj7mQSJEwCGlonChww8neeSiJ5+dEyztvsRjfeDCq",
	"wSGgPEmtLsOQmQs0OpHGg2tmeM6CRgp8L3EuffIgpiyqUTV7xXcp1Q8v9juml/k+bsNGY9ct8ypI3Lty",
	"LhyqWqKY/w0CjUtMpQSuc5aIMUVNfLs76pIluyQ5qp5c+56QS8rZH1Tno257c+w+u/a9BGTMUB4UgWmI",
	"1a4xTsp3zAj5MqmU1LD3lLMPKYzsOIbZOptLo2i88Prvtg9vN/fcb2OawAICzTKDPJWk139XBnGG6EsF",
	"gabSoFSKKHfeOWzNhaVMDeEJwTof9CIOG2+f5b6XKnvcbxP1TOUBhosDfLGhFd9Vbr4h9c2vydOFngPI",
	"WAAbwROg/YQzqmsGEFINzzSLwesAfWAB6Sx/LkQEFPUKVwmToG414IatjKjSM2o0B7caTmmq051wzLfk",
	"1D7c1AbGWvlAvrtLLbFqS642p0sX9VOipQswtztUJMIOX/3q+nPIlgLDknkEe3g+IO/o4Gw+uSNP95s0",
	"Pb9wi8BnC2Mu7jbOvNZL7qnmt4mVT1pR47aAy98cb/lkIw0iK7KFYJhTK6FagzS6+Z93g2d/PTf/7D/7",
	"8+z8P//UhdIQNGWR2nxW2fi+BaIYlKJL6LQYaTllt29qIBxhVQ3XxmvznEJ0dsG6On07ML3xbG0Jf3fP",
	"sSPFcrNj2p4fN/Ue1ZoLB+J7asWD2Q2dz4oH2zxPjRQ4jqjmatz5tuvlkNlAo66b8tS+0fHtaLl5fBtC",
	"kENyKwGgSxjxhWgvGefPB9m+ktNyexvukAURHtSZiQXwIP/ZydqEQBTjgRTmaLUUVgGBKyMiSYQkChJq",
	"aLhLPxPgoQGQ79EggESDzb9l4j3+z+oi7KSllml1bPmXwmtF/e6N13twHFxtTnSa0N6FZruCh0Byrpwn",
	"R/FRjajfCxj3psSW6trchbGsTBAaxTQAbswFODkRSi8lnP7lcO8+KOsCQF3z23eqsvcuqzQcDG0yFhna",
	"5IeUSso14xvsctyIee6kBJuW//To2rH5JRMBSFDX/zBxckRSlVLJUEXGt5EiXrDBOKoqSped4t1Mh+4W",
	"Ob7iI9PB5ey9rTA10/hlJC8SGlBDQ0NKrv/JWUBtqsLEVDaEUqAHqLfvMF/aFvLhDlHUU74fjqMp4LfD",
	"37j78BBepxlCP63v6dCqa1NSZMxEQw3DUqky5oamFTJlAo1uuyoFa20Shys9C8qyJ0+jPPNWo7fVSFpo",
	"ioSxrM3td9bm3NXbd7qW7eQcWrC19wQGTk6GQLLMMgabAijuuMTAjdH7GYOPjbi9nyaGtRp4A42LJ/D/",
	"Np5vPJBftG6suFhVTPs2/Oy4EVNuFJ7fwDyccZr9Ir1WpQdU/mxfQbToVGGREiwXaUYzYNidhJuk3BD0",
	"V5jNvGXyjab68pavFFlTCLtTEIjm0FKUYjWBcT6dwifpPGLq0oCy272dSLDZZsXIqshyMnJRiXFBQBGD",
	"573O+q4L1VI2313GzuALd6kL4HkW4yEcVD1T9OQeqp6PaWlhaIk8N4dzxP7ISX1EiQKFfJ5xPLhDgXw+",
	"z9c5ueQ55aHg6MpK/1ZxicLLFaTeJRUSkogGNfbfBSTnOHKA9yGFFF+t5jInD15aULbJoU5zCx4XNn2X",
	"xHbVoHCjPgRXXdWrXbo6Q/eVt0fcQbAHSJtvTJdb2dzz7i4SFhzPqQA8f7G/q6miLiKO0Smi6ooNaUY1",
	"lbNU1vMlqWSGy+w6N0OmkoiuZhvJ6S0yMXcBTC1tUROm07kpCFLJ9OrUaNuufw5Ughzk54H963Uhw3//",
	"NvWaTHkq3gPH0D53AWj0P2PN3mXFBO2d+iRIsRCFkT9bgk8yloFh0ipVJIgoixXJQLIFC2go1F7RRoTn",
	"C8pTbcOl1lhFURm7GoVtf2U7KOxIkiyYdU2GVUAGXAunnGnm6ezZMmM/c/eeJuwtrIppT4196FR2ZIdb",
	"FdOARkEaGVquxFwCgYjMRbgiQrIl4zTaLoMqZ9ogypTFJhqJk7Yo5a37bIIux28JYNDEcurZaBc4GRGs",
	"VQuubTh1sopBkezFHjnsxghRDOJEYj0ywyKmEVYboOHZzrQxQa8YhwxORp7vZSAtxfT2957v7WNxLQFO",
	"E+b1vR/29vd+sOnhS8R5jyaslz3vNetvCdUBQh8bTtBxhV4/92d5EXBcrw65zYUbos3qkV6jU9CEnnnC",
	"+KUIVw9WC9/kgNd1l1EU+dwmtBf7Lx5MjHq81dFMgo1cpf7L2p9FKTVUr5ExNIxAU+MvMJ7BYPvH/f1N",
	"gpQr6zndHvjK892v1Bot8KUfdr9UNYrhG3/e/UbZV7f2vZ9uMoXbPGH2VNOlwV49sXJu7nTBHJW8BN22",
	"VUNgKYmocsxScFBWL6By+1RojyrFg4TQoh8oFHvkWBAEF0ggKd9g3oClXbRnsiI85QElJrpqzmqES+cM",
	"pKaqlsgIQVXVYL9hqmYRR6txbcG3NdK8Q3jt73zStsFaK67Z0P6j2BCGGB12NN6tryJn5errKY3nXsi2",
	"B7le1VEtbcj7LChj3hzWdUS8AV0Pjh9RWfWJNrS0YreRNYnk+p9zMxXhEICiklFi0EUYZwGj0tCojzDf",
	"q9E1r//uvNqafMb6zqiq1WDTljQ6Wh5xTxozbet09RseY0Vsn4VQZQ5I7T2h/34E0Ba5oB1eGK6CKFUs",
	"y12eYddo2kG6sr2ULARJUgWSBILxgIVlr9edPfMmZ3oKZaPLv7AfdbM0nc2B+Q6baBA42OZqReiXd50/",
	"vrgBi3C7th8Xub1PVbvT2uI3At3VygiZCCjCrYgObebObQEzgkkxpxJjQJAZM7HahxRKRYDRQSeoJ5CA",
	"ZuglJc5l0QzKxJZaKNFG9ASTRyWmbw3p6nciN0B1J9mvwfvH9q6d5ltlVxRSIsjKHAhwxZRZO/y7cd6v",
	"BN4aaNyr8vpq4+FpPMgUaDxynn10z+h3/9KqqtzfyAe2O2Ye1eU2ml+6Tv68nzkn/JvSRl855O+FRgMl",
	"73zte4lQHWizzdV1vH2tWYfuRvAnzjm4PVKbAYfnBA9EREP6LYnQhuMWx9j7VPsh6bqHtTlMv3ZDeIL3",
	"7wth9/etD3L2PhXkJgA8u/6HKPD2LWl1b7wZDrcNb+b+/2O8OVT4m4u7MeTyn3ns5H15Y9y/djTsdHJ2",
	"QOiIQTyXIs8gim5q5lRl/u3Z2Qas9D6VNfpGJNz0SLHIoALPrbFTfgXhK/NERRtvV2kHf6duSzrzSHxI",
	"gYaCrLCC06jlfPNRW6KCbRXJL4moxypauh0tTxw6bEbzKxrPmSA0gETTUGB/Q7M0WfbXkiQFm47VjKc2",
	"szWnwfulFCkPv8F8t3stuyiflV2UG9leq0vra42ON7STfTUYn9Z+D65gmZaFqG/OeRNq8w8JqJ5tbnVQ",
	"2mid5Bo/kFF0NhQFbNt3Q44F/m60ar/6GevwWoIiAZ1DABLruPZ9ogQnYh6xJdVCMqrIyjik/B6QjNrP",
	"xdS6jPDjMZEGSWVXWjwAlgGKlH+iwbu7Fdzit5Q3AX9HknxoW5eqRjGyKp1z3mCAX2z4mUSGvaYobSgU",
	"0caRX/8df3omIRBcBLchsO1Ph9wU410f77gpDjs+mtEoCH8qe+Denbca04pLToPYu/O1U0POx1cG081x",
	"3Y5A+5YCmRWeFRslvZ7njFb0bZaVaUMwqg+g2cy7c63xm4zyOhqZ83cp5Pp8/X8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
