DROP VIEW IF EXISTS suppliers;
DROP VIEW IF EXISTS customers;
ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS user_roles_party_id_fkey;
ALTER TABLE org_members DROP CONSTRAINT IF EXISTS org_members_party_id_fkey;
ALTER TABLE ai_conversations DROP CONSTRAINT IF EXISTS ai_conversations_agent_party_id_fkey;
ALTER TABLE payment_preferences DROP CONSTRAINT IF EXISTS payment_preferences_party_id_fkey;
ALTER TABLE accounts DROP CONSTRAINT IF EXISTS accounts_party_id_fkey;
ALTER TABLE credit_notes DROP CONSTRAINT IF EXISTS credit_notes_party_id_fkey;
ALTER TABLE appointments DROP CONSTRAINT IF EXISTS appointments_party_id_fkey;
ALTER TABLE recurring_expenses DROP CONSTRAINT IF EXISTS recurring_expenses_party_id_fkey;
ALTER TABLE purchases DROP CONSTRAINT IF EXISTS purchases_party_id_fkey;
ALTER TABLE sales DROP CONSTRAINT IF EXISTS sales_party_id_fkey;
ALTER TABLE quotes DROP CONSTRAINT IF EXISTS quotes_party_id_fkey;
ALTER TABLE user_roles DROP COLUMN IF EXISTS party_id;
ALTER TABLE org_members DROP COLUMN IF EXISTS party_id;
ALTER TABLE ai_conversations DROP COLUMN IF EXISTS agent_party_id;
ALTER TABLE payment_preferences DROP COLUMN IF EXISTS party_id;
ALTER TABLE audit_log DROP COLUMN IF EXISTS actor_label;
ALTER TABLE audit_log DROP COLUMN IF EXISTS actor_id;
ALTER TABLE audit_log DROP COLUMN IF EXISTS actor_type;
DROP TABLE IF EXISTS party_relationships;
DROP TABLE IF EXISTS party_roles;
DROP TABLE IF EXISTS party_agents;
DROP TABLE IF EXISTS party_organizations;
DROP TABLE IF EXISTS party_persons;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS parties;
