package dashboard

import dashboarddomain "github.com/devpablocristo/pymes/pymes-core/backend/internal/dashboard/usecases/domain"

func fixedDashboardWidgets() []dashboarddomain.WidgetDefinition {
	return []dashboarddomain.WidgetDefinition{
		{
			WidgetKey:         "sales.summary",
			Title:             "Ventas del periodo",
			Description:       "Resumen operativo de ventas completadas del periodo actual.",
			Domain:            "control-plane",
			Kind:              "metric",
			SupportedContexts: []string{"home"},
			AllowedRoles:      []string{"owner", "admin", "member", "service"},
			SettingsSchema:    map[string]any{},
			DataEndpoint:      "/v1/dashboard-data/sales-summary",
			Status:            "active",
		},
		{
			WidgetKey:         "cashflow.summary",
			Title:             "Cashflow resumido",
			Description:       "Ingresos, egresos y balance del periodo.",
			Domain:            "control-plane",
			Kind:              "metric",
			SupportedContexts: []string{"home"},
			AllowedRoles:      []string{"owner", "admin", "member", "service"},
			SettingsSchema:    map[string]any{},
			DataEndpoint:      "/v1/dashboard-data/cashflow-summary",
			Status:            "active",
		},
		{
			WidgetKey:         "quotes.pipeline",
			Title:             "Presupuestos abiertos",
			Description:       "Pipeline de presupuestos por estado.",
			Domain:            "control-plane",
			Kind:              "metric",
			SupportedContexts: []string{"home"},
			AllowedRoles:      []string{"owner", "admin", "member", "service"},
			SettingsSchema:    map[string]any{},
			DataEndpoint:      "/v1/dashboard-data/quotes-pipeline",
			Status:            "active",
		},
		{
			WidgetKey:         "inventory.low_stock",
			Title:             "Alertas de stock",
			Description:       "Productos por debajo del minimo definido.",
			Domain:            "control-plane",
			Kind:              "list",
			SupportedContexts: []string{"home"},
			AllowedRoles:      []string{"owner", "admin", "member", "service"},
			SettingsSchema:    map[string]any{},
			DataEndpoint:      "/v1/dashboard-data/low-stock",
			Status:            "active",
		},
		{
			WidgetKey:         "sales.recent",
			Title:             "Ventas recientes",
			Description:       "Ultimas ventas registradas en la organizacion.",
			Domain:            "control-plane",
			Kind:              "feed",
			SupportedContexts: []string{"home"},
			AllowedRoles:      []string{"owner", "admin", "member", "service"},
			SettingsSchema:    map[string]any{},
			DataEndpoint:      "/v1/dashboard-data/recent-sales",
			Status:            "active",
		},
		{
			WidgetKey:         "products.top",
			Title:             "Top productos",
			Description:       "Productos con mayor facturacion en el periodo.",
			Domain:            "control-plane",
			Kind:              "list",
			SupportedContexts: []string{"home"},
			AllowedRoles:      []string{"owner", "admin", "member", "service"},
			SettingsSchema:    map[string]any{},
			DataEndpoint:      "/v1/dashboard-data/top-products",
			Status:            "active",
		},
		{
			WidgetKey:         "services.top",
			Title:             "Top servicios",
			Description:       "Servicios con mayor facturacion en el periodo.",
			Domain:            "control-plane",
			Kind:              "list",
			SupportedContexts: []string{"home"},
			AllowedRoles:      []string{"owner", "admin", "member", "service"},
			SettingsSchema:    map[string]any{},
			DataEndpoint:      "/v1/dashboard-data/top-services",
			Status:            "active",
		},
		{
			WidgetKey:         "billing.subscription",
			Title:             "Estado del plan",
			Description:       "Plan actual, estado de facturacion y limites.",
			Domain:            "control-plane",
			Kind:              "status",
			SupportedContexts: []string{"home"},
			AllowedRoles:      []string{"owner", "admin"},
			SettingsSchema:    map[string]any{},
			DataEndpoint:      "/v1/dashboard-data/billing-status",
			Status:            "active",
		},
		{
			WidgetKey:         "audit.activity",
			Title:             "Actividad reciente",
			Description:       "Ultimos eventos relevantes del tenant.",
			Domain:            "control-plane",
			Kind:              "feed",
			SupportedContexts: []string{"home"},
			AllowedRoles:      []string{"owner", "admin", "member", "service"},
			SettingsSchema:    map[string]any{},
			DataEndpoint:      "/v1/dashboard-data/audit-activity",
			Status:            "active",
		},
	}
}
