FROM python:3.12-slim
WORKDIR /workspace/professionals/ai
COPY professionals/ai/requirements.txt ./
COPY pkgs/py-pkg /workspace/pkgs/py-pkg
RUN pip install --no-cache-dir -r requirements.txt
COPY professionals/ai/src/ ./src/
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
