FROM python:3.12-slim

WORKDIR /workspace/ai

COPY ai/requirements.txt ./
COPY control-plane/shared/ai /workspace/control-plane/shared/ai
COPY pkgs/py-pkg /workspace/pkgs/py-pkg
RUN pip install --no-cache-dir -r requirements.txt

COPY ai/src/ ./src/

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
