FROM golang:1.26.5-alpine

RUN apk add --no-cache ca-certificates git \
    && GOBIN=/usr/local/bin go install github.com/air-verse/air@v1.62.0

WORKDIR /src

COPY go.mod go.sum ./
RUN GOWORK=off go mod download

COPY . .

ENTRYPOINT ["air"]
CMD ["-c", ".air.api.toml"]
