FROM golang:1.25-alpine

RUN apk add --no-cache git curl && \
    curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /workspace

COPY go.mod go.sum ./

WORKDIR /workspace/control-plane/backend

RUN go mod download

COPY control-plane/backend /workspace/control-plane/backend
COPY control-plane/shared/backend /workspace/control-plane/shared/backend
COPY pkgs/go-pkg /workspace/pkgs/go-pkg

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
