/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/runtime-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRuntimeConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista las organizaciones locales activas del subject autenticado. No requiere una organización activa en el token y nunca crea organizaciones descubiertas únicamente desde Clerk. */
        get: operations["listMyOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCurrentOrganization"];
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista exclusivamente sesiones cuyo provider user coincide con el subject autenticado. No requiere una organización activa. */
        get: operations["listMySessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Revoca una sesión sólo después de comprobar en servidor que pertenece al subject autenticado. Repetir la revocación es exitoso. */
        delete: operations["revokeMySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTeamMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeTeamMember"];
        options?: never;
        head?: never;
        patch: operations["updateTeamMember"];
        trace?: never;
    };
    "/api/v1/team/ownership-transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["transferOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTeamInvitations"];
        put?: never;
        post: operations["createTeamInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/invitations/{invitation_id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendTeamInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/invitations/{invitation_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeTeamInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Entrada firmada de Clerk/Svix. No usa bearerAuth; las tres cabeceras de firma son obligatorias y la firma se valida sobre el body sin alterar. */
        post: operations["receiveClerkWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "owner" | "admin" | "member";
        /**
         * @description Permiso IAM efectivo derivado del rol efectivo.
         * @enum {string}
         */
        Permission: "organization:view" | "organization:update" | "team:view" | "team:member:update" | "team:member:remove" | "team:invitation:create" | "team:invitation:manage" | "team:ownership:transfer" | "sessions:manage:self";
        /**
         * @description Roles administrables mediante invitación o edición. `owner` sólo se obtiene con el comando atómico de transferencia de propiedad.
         * @enum {string}
         */
        AssignableRole: "admin" | "member";
        /** @enum {string} */
        OrganizationStatus: "provisioning" | "active" | "suspended" | "disabled";
        /** @enum {string} */
        SyncStatus: "queued" | "pending" | "synced" | "failed";
        /** @enum {string} */
        MembershipStatus: "pending" | "active" | "removed" | "quarantined";
        /**
         * @description Ciclo de vida local; el estado de sincronización se expone por separado.
         * @enum {string}
         */
        InvitationStatus: "pending" | "accepted" | "revoked" | "expired";
        /**
         * @description Estado normalizado de la sesión informado por Clerk.
         * @enum {string}
         */
        SessionStatus: "abandoned" | "active" | "pending" | "ended" | "expired" | "removed" | "replaced" | "revoked";
        RuntimeConfig: {
            auth: {
                /** @enum {string} */
                provider: "clerk";
                configured: boolean;
                /** @description Presente si y sólo si `configured` es true. */
                publishable_key?: string;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** Format: uri */
            avatar_url?: string | null;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: components["schemas"]["OrganizationStatus"];
            /** @description Rol local de la membresía del usuario en esta organización. */
            role: components["schemas"]["Role"];
            /** @description Referencia opaca usada únicamente con Clerk.setActive(). */
            switch_key?: string;
            sync_status: components["schemas"]["SyncStatus"];
        };
        Membership: {
            /** Format: uuid */
            id: string;
            /** @description Rol local autoritativo almacenado en PostgreSQL. */
            role: components["schemas"]["Role"];
            status: components["schemas"]["MembershipStatus"];
        };
        CurrentSession: {
            user: components["schemas"]["User"];
            organization: components["schemas"]["Organization"];
            membership: components["schemas"]["Membership"];
            /** @description Rol efectivo después de intersectar el rol local con el rol grueso de Clerk. */
            role: components["schemas"]["Role"];
            permissions: components["schemas"]["Permission"][];
            session_id: string;
        };
        DeviceSession: {
            id: string;
            status: components["schemas"]["SessionStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_active_at: string;
            /** Format: date-time */
            expires_at: string;
            current: boolean;
        };
        Member: {
            /** Format: uuid */
            id: string;
            user: components["schemas"]["User"];
            role: components["schemas"]["Role"];
            status: components["schemas"]["MembershipStatus"];
            sync_status: components["schemas"]["SyncStatus"];
        };
        Invitation: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["InvitationStatus"];
            /** Format: date-time */
            expires_at: string;
            sync_status: components["schemas"]["SyncStatus"];
        };
        PageInfo: {
            total: number;
            next_cursor?: string | null;
        };
        OrganizationList: {
            items: components["schemas"]["Organization"][];
            page: components["schemas"]["PageInfo"];
        };
        SessionList: {
            items: components["schemas"]["DeviceSession"][];
            page: components["schemas"]["PageInfo"];
        };
        MemberList: {
            items: components["schemas"]["Member"][];
            page: components["schemas"]["PageInfo"];
        };
        InvitationList: {
            items: components["schemas"]["Invitation"][];
            page: components["schemas"]["PageInfo"];
        };
        UpdateOrganizationInput: {
            name: string;
        };
        UpdateMemberInput: {
            role: components["schemas"]["AssignableRole"];
        };
        TransferOwnershipInput: {
            /** Format: uuid */
            member_id: string;
        };
        CreateInvitationInput: {
            /** Format: email */
            email: string;
            role: components["schemas"]["AssignableRole"];
        };
        ErrorResponse: {
            error: {
                /** @description Código estable. IAM usa `AUTH_INVALID_TOKEN`, `AUTH_ORGANIZATION_REQUIRED`, `IAM_MEMBERSHIP_REQUIRED`, `IAM_FORBIDDEN`, `IAM_ROLE_CONFLICT`, `IAM_INVITATION_PENDING`, `AUTH_PROVIDER_RATE_LIMITED`, `AUTH_NOT_CONFIGURED`, `AUTH_PROVIDER_UNAVAILABLE`, `IAM_UNAVAILABLE`, `REQUEST_INVALID`, `IDEMPOTENCY_KEY_CONFLICT`, `IDEMPOTENCY_IN_PROGRESS`, `WEBHOOK_INVALID_PAYLOAD` y `WEBHOOK_INVALID_SIGNATURE`. */
                code: string;
                message: string;
                request_id?: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Request inválido (`REQUEST_INVALID`). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Credencial ausente o inválida (`AUTH_INVALID_TOKEN`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Identidad válida sin acceso suficiente (`AUTH_ORGANIZATION_REQUIRED`, `IAM_MEMBERSHIP_REQUIRED` o `IAM_FORBIDDEN`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflicto con el estado actual (`IAM_ROLE_CONFLICT`, `IAM_INVITATION_PENDING`, `IDEMPOTENCY_KEY_CONFLICT` o `IDEMPOTENCY_IN_PROGRESS`). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Clerk limitó temporalmente la operación (`AUTH_PROVIDER_RATE_LIMITED`). */
        RateLimited: {
            headers: {
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Autenticación no configurada (`AUTH_NOT_CONFIGURED`) o proveedor temporalmente indisponible (`AUTH_PROVIDER_UNAVAILABLE`). Una falla temporal de la autoridad IAM local usa `IAM_UNAVAILABLE`. */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Payload de webhook inválido (`WEBHOOK_INVALID_PAYLOAD`). */
        WebhookBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Firma Clerk/Svix ausente o inválida (`WEBHOOK_INVALID_SIGNATURE`). */
        WebhookUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Secreto de webhook no configurado (`AUTH_NOT_CONFIGURED`) o inbox IAM temporalmente indisponible (`IAM_UNAVAILABLE`). */
        WebhookUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
        IdempotencyKey: string;
        SessionID: string;
        MemberID: string;
        InvitationID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRuntimeConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuración pública necesaria para iniciar la web. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identidad, organización y permisos efectivos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    listMyOrganizations: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organizaciones locales activas del usuario autenticado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateCurrentOrganization: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationInput"];
            };
        };
        responses: {
            /** @description Actualización local confirmada y sincronización remota en curso. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    listMySessions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesiones pertenecientes al usuario autenticado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    revokeMySession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión revocada o ya inexistente. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    listTeamMembers: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Miembros activos de la organización del token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    removeTeamMember: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                member_id: components["parameters"]["MemberID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acceso local bloqueado y remoción remota encolada. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateTeamMember: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                member_id: components["parameters"]["MemberID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberInput"];
            };
        };
        responses: {
            /** @description Cambio aceptado; la sincronización con Clerk puede continuar en background. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    transferOwnership: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOwnershipInput"];
            };
        };
        responses: {
            /** @description Transferencia segura iniciada. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    listTeamInvitations: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["InvitationStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitaciones de la organización activa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    createTeamInvitation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationInput"];
            };
        };
        responses: {
            /** @description Invitación encolada. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    resendTeamInvitation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reenvío encolado. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    revokeTeamInvitation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revocación encolada. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    receiveClerkWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Evento verificado y aceptado en el inbox; los duplicados también se reconocen. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["WebhookBadRequest"];
            401: components["responses"]["WebhookUnauthorized"];
            503: components["responses"]["WebhookUnavailable"];
        };
    };
}
