/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/runtime-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRuntimeConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista las organizaciones locales activas del subject autenticado. No requiere una organización activa en el token y nunca crea organizaciones descubiertas únicamente desde Clerk. */
        get: operations["listMyOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista global de tenants; requiere rol global owner. */
        get: operations["listAdminTenants"];
        put?: never;
        post: operations["createAdminTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAdminTenant"];
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenant_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveAdminTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenant_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unarchiveAdminTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenant_id}/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trashAdminTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenant_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreAdminTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenants/{tenant_id}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Purga irreversible; sólo admite tenants en la papelera. */
        delete: operations["purgeAdminTenant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminUsers"];
        put?: never;
        /** @description Invita por email a un usuario y lo asigna a un tenant. */
        post: operations["createAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAdminUser"];
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unarchiveAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/trash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["trashAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Purga irreversible; exige usuario en la papelera. */
        delete: operations["purgeAdminUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCurrentOrganization"];
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lista exclusivamente sesiones cuyo provider user coincide con el subject autenticado. No requiere una organización activa. */
        get: operations["listMySessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Revoca una sesión sólo después de comprobar en servidor que pertenece al subject autenticado. Repetir la revocación es exitoso. */
        delete: operations["revokeMySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTeamMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeTeamMember"];
        options?: never;
        head?: never;
        patch: operations["updateTeamMember"];
        trace?: never;
    };
    "/api/v1/team/ownership-transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @deprecated
         * @description Compatibilidad temporal. La propiedad ya no pertenece al tenant: `owner` es un rol global de Pymes administrado mediante `/api/v1/admin/users`. Este endpoint siempre responde `409`.
         */
        post: operations["transferOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTeamInvitations"];
        put?: never;
        post: operations["createTeamInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/invitations/{invitation_id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendTeamInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/team/invitations/{invitation_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeTeamInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Entrada firmada de Clerk/Svix. No usa bearerAuth; las tres cabeceras de firma son obligatorias y la firma se valida sobre el body sin alterar. */
        post: operations["receiveClerkWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Rol efectivo; `owner` es global y las membresías tenant usan `admin|member`.
         * @enum {string}
         */
        Role: "owner" | "admin" | "member";
        /**
         * @description Rol global del producto; `owner` tiene autoridad sobre todos los tenants y usuarios.
         * @enum {string}
         */
        ProductRole: "owner" | "user";
        /** @enum {string} */
        UserStatus: "active" | "disabled";
        /**
         * @description Estado canónico administrado por Platform lifecycle.
         * @enum {string}
         */
        LifecycleState: "active" | "archived" | "trashed";
        /**
         * @description Permiso IAM efectivo derivado del rol efectivo.
         * @enum {string}
         */
        Permission: "organization:view" | "organization:update" | "team:view" | "team:member:update" | "team:member:remove" | "team:invitation:create" | "team:invitation:manage" | "sessions:manage:self";
        /**
         * @description Roles administrables dentro de un tenant. `owner` es un rol global del producto y no forma parte de una membresía.
         * @enum {string}
         */
        AssignableRole: "admin" | "member";
        /** @enum {string} */
        OrganizationStatus: "provisioning" | "active" | "suspended" | "disabled";
        /** @enum {string} */
        SyncStatus: "queued" | "pending" | "synced" | "failed";
        /** @enum {string} */
        MembershipStatus: "pending" | "active" | "removed" | "quarantined";
        /**
         * @description Ciclo de vida local; el estado de sincronización se expone por separado.
         * @enum {string}
         */
        InvitationStatus: "pending" | "accepted" | "revoked" | "expired";
        /**
         * @description Estado normalizado de la sesión informado por Clerk.
         * @enum {string}
         */
        SessionStatus: "abandoned" | "active" | "pending" | "ended" | "expired" | "removed" | "replaced" | "revoked";
        RuntimeConfig: {
            auth: {
                /** @enum {string} */
                provider: "clerk";
                configured: boolean;
                /** @description Presente si y sólo si `configured` es true. */
                publishable_key?: string;
            };
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** Format: uri */
            avatar_url?: string | null;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: components["schemas"]["OrganizationStatus"];
            /** @description Rol local de la membresía del usuario en esta organización. */
            role: components["schemas"]["Role"];
            /** @description Referencia opaca usada únicamente con Clerk.setActive(). */
            switch_key?: string;
            sync_status: components["schemas"]["SyncStatus"];
        };
        AdminTenant: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            status: components["schemas"]["OrganizationStatus"];
            lifecycle_state: components["schemas"]["LifecycleState"];
            /** Format: date-time */
            archived_at?: string | null;
            /** Format: date-time */
            trashed_at?: string | null;
            /** Format: date-time */
            purge_after?: string | null;
            sync_status: components["schemas"]["SyncStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminMembership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            tenant_name: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["MembershipStatus"];
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            email_verified: boolean;
            display_name: string;
            /** Format: uri */
            avatar_url?: string | null;
            status: components["schemas"]["UserStatus"];
            lifecycle_state: components["schemas"]["LifecycleState"];
            /** Format: date-time */
            archived_at?: string | null;
            /** Format: date-time */
            trashed_at?: string | null;
            /** Format: date-time */
            purge_after?: string | null;
            product_role: components["schemas"]["ProductRole"];
            memberships: components["schemas"]["AdminMembership"][];
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Membership: {
            /** Format: uuid */
            id: string;
            /** @description Rol local autoritativo almacenado en PostgreSQL. */
            role: components["schemas"]["Role"];
            status: components["schemas"]["MembershipStatus"];
        };
        CurrentSession: {
            user: components["schemas"]["User"];
            organization: components["schemas"]["Organization"];
            membership: components["schemas"]["Membership"];
            /** @description Rol efectivo después de intersectar el rol local con el rol grueso de Clerk. */
            role: components["schemas"]["Role"];
            permissions: components["schemas"]["Permission"][];
            session_id: string;
        };
        DeviceSession: {
            id: string;
            status: components["schemas"]["SessionStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_active_at: string;
            /** Format: date-time */
            expires_at: string;
            current: boolean;
        };
        Member: {
            /** Format: uuid */
            id: string;
            user: components["schemas"]["User"];
            role: components["schemas"]["Role"];
            status: components["schemas"]["MembershipStatus"];
            sync_status: components["schemas"]["SyncStatus"];
        };
        Invitation: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["InvitationStatus"];
            /** Format: date-time */
            expires_at: string;
            sync_status: components["schemas"]["SyncStatus"];
        };
        PageInfo: {
            total: number;
            next_cursor?: string | null;
        };
        OrganizationList: {
            items: components["schemas"]["Organization"][];
            page: components["schemas"]["PageInfo"];
            product_role: components["schemas"]["ProductRole"];
        };
        AdminTenantList: {
            items: components["schemas"]["AdminTenant"][];
            page: components["schemas"]["PageInfo"];
        };
        AdminUserList: {
            items: components["schemas"]["AdminUser"][];
            page: components["schemas"]["PageInfo"];
        };
        SessionList: {
            items: components["schemas"]["DeviceSession"][];
            page: components["schemas"]["PageInfo"];
        };
        MemberList: {
            items: components["schemas"]["Member"][];
            page: components["schemas"]["PageInfo"];
        };
        InvitationList: {
            items: components["schemas"]["Invitation"][];
            page: components["schemas"]["PageInfo"];
        };
        UpdateOrganizationInput: {
            name: string;
        };
        CreateAdminTenantInput: {
            name: string;
            slug: string;
            /** Format: email */
            admin_email: string;
        };
        UpdateAdminTenantInput: {
            name?: string;
            slug?: string;
        };
        CreateAdminUserInput: {
            /** Format: email */
            email: string;
            /** Format: uuid */
            tenant_id: string;
            role: components["schemas"]["Role"];
        };
        UpdateAdminUserInput: {
            display_name?: string;
            /** Format: email */
            email?: string;
            product_role?: components["schemas"]["ProductRole"];
            /** Format: int64 */
            version: number;
        };
        LifecycleCommandInput: {
            reason?: string;
        };
        UpdateMemberInput: {
            role: components["schemas"]["AssignableRole"];
        };
        TransferOwnershipInput: {
            /** Format: uuid */
            member_id: string;
        };
        CreateInvitationInput: {
            /** Format: email */
            email: string;
            role: components["schemas"]["AssignableRole"];
        };
        ErrorResponse: {
            error: {
                /** @description Código estable. IAM usa `AUTH_INVALID_TOKEN`, `AUTH_ORGANIZATION_REQUIRED`, `IAM_MEMBERSHIP_REQUIRED`, `IAM_FORBIDDEN`, `IAM_ROLE_CONFLICT`, `IAM_INVITATION_PENDING`, `AUTH_PROVIDER_RATE_LIMITED`, `AUTH_NOT_CONFIGURED`, `AUTH_PROVIDER_UNAVAILABLE`, `IAM_UNAVAILABLE`, `REQUEST_INVALID`, `IDEMPOTENCY_KEY_CONFLICT`, `IDEMPOTENCY_IN_PROGRESS`, `WEBHOOK_INVALID_PAYLOAD` y `WEBHOOK_INVALID_SIGNATURE`. */
                code: string;
                message: string;
                request_id?: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Request inválido (`REQUEST_INVALID`). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Credencial ausente o inválida (`AUTH_INVALID_TOKEN`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Identidad válida sin acceso suficiente (`AUTH_ORGANIZATION_REQUIRED`, `IAM_MEMBERSHIP_REQUIRED` o `IAM_FORBIDDEN`). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Recurso inexistente o no visible (`RESOURCE_NOT_FOUND`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflicto con el estado actual (`IAM_ROLE_CONFLICT`, `IAM_INVITATION_PENDING`, `IDEMPOTENCY_KEY_CONFLICT` o `IDEMPOTENCY_IN_PROGRESS`). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Clerk limitó temporalmente la operación (`AUTH_PROVIDER_RATE_LIMITED`). */
        RateLimited: {
            headers: {
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Autenticación no configurada (`AUTH_NOT_CONFIGURED`) o proveedor temporalmente indisponible (`AUTH_PROVIDER_UNAVAILABLE`). Una falla temporal de la autoridad IAM local usa `IAM_UNAVAILABLE`. */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Payload de webhook inválido (`WEBHOOK_INVALID_PAYLOAD`). */
        WebhookBadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Firma Clerk/Svix ausente o inválida (`WEBHOOK_INVALID_SIGNATURE`). */
        WebhookUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Secreto de webhook no configurado (`AUTH_NOT_CONFIGURED`) o inbox IAM temporalmente indisponible (`IAM_UNAVAILABLE`). */
        WebhookUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Cursor: string;
        Limit: number;
        IdempotencyKey: string;
        SessionID: string;
        MemberID: string;
        InvitationID: string;
        TenantID: string;
        UserID: string;
    };
    requestBodies: {
        LifecycleCommand: {
            content: {
                "application/json": components["schemas"]["LifecycleCommandInput"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRuntimeConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuración pública necesaria para iniciar la web. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
        };
    };
    getCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identidad, organización y permisos efectivos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    listMyOrganizations: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organizaciones locales activas del usuario autenticado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    listAdminTenants: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["OrganizationStatus"];
                lifecycle_state?: components["schemas"]["LifecycleState"];
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenants visibles para el owner global. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTenantList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    createAdminTenant: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminTenantInput"];
            };
        };
        responses: {
            /** @description Provisionamiento local confirmado y sincronización con Clerk en curso. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    getAdminTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant global. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTenant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateAdminTenant: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAdminTenantInput"];
            };
        };
        responses: {
            /** @description Tenant actualizado localmente. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminTenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    archiveAdminTenant: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LifecycleCommand"];
        responses: {
            /** @description Tenant archivado y excluido de los flujos activos. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    unarchiveAdminTenant: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LifecycleCommand"];
        responses: {
            /** @description Tenant desarchivado y nuevamente activo. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    trashAdminTenant: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LifecycleCommand"];
        responses: {
            /** @description Tenant movido a la papelera. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    restoreAdminTenant: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LifecycleCommand"];
        responses: {
            /** @description Tenant restaurado desde la papelera. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    purgeAdminTenant: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                tenant_id: components["parameters"]["TenantID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LifecycleCommand"];
        responses: {
            /** @description Tenant purgado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    listAdminUsers: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["UserStatus"];
                lifecycle_state?: components["schemas"]["LifecycleState"];
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuarios globales. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    createAdminUser: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminUserInput"];
            };
        };
        responses: {
            /** @description Invitación creada. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    getAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuario global. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateAdminUser: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAdminUserInput"];
            };
        };
        responses: {
            /** @description Usuario actualizado. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    archiveAdminUser: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LifecycleCommand"];
        responses: {
            /** @description Usuario archivado y acceso cortado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    unarchiveAdminUser: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LifecycleCommand"];
        responses: {
            /** @description Usuario desarchivado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    trashAdminUser: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LifecycleCommand"];
        responses: {
            /** @description Usuario movido a la papelera y acceso cortado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    restoreAdminUser: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LifecycleCommand"];
        responses: {
            /** @description Usuario restaurado desde la papelera. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    purgeAdminUser: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                user_id: components["parameters"]["UserID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LifecycleCommand"];
        responses: {
            /** @description Usuario purgado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateCurrentOrganization: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationInput"];
            };
        };
        responses: {
            /** @description Actualización local confirmada y sincronización remota en curso. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    listMySessions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesiones pertenecientes al usuario autenticado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    revokeMySession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión revocada o ya inexistente. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Unavailable"];
        };
    };
    listTeamMembers: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Miembros activos de la organización del token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    removeTeamMember: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                member_id: components["parameters"]["MemberID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acceso local bloqueado y remoción remota encolada. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    updateTeamMember: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                member_id: components["parameters"]["MemberID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberInput"];
            };
        };
        responses: {
            /** @description Cambio aceptado; la sincronización con Clerk puede continuar en background. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    transferOwnership: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOwnershipInput"];
            };
        };
        responses: {
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    listTeamInvitations: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                status?: components["schemas"]["InvitationStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitaciones de la organización activa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["Unavailable"];
        };
    };
    createTeamInvitation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvitationInput"];
            };
        };
        responses: {
            /** @description Invitación encolada. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    resendTeamInvitation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reenvío encolado. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    revokeTeamInvitation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                invitation_id: components["parameters"]["InvitationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revocación encolada. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invitation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    receiveClerkWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Evento verificado y aceptado en el inbox; los duplicados también se reconocen. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["WebhookBadRequest"];
            401: components["responses"]["WebhookUnauthorized"];
            503: components["responses"]["WebhookUnavailable"];
        };
    };
}
