// Package fiscalapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package fiscalapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	AUTHORITYTIMEOUT     ErrorCode = "AUTHORITY_TIMEOUT"
	IDEMPOTENCYKEYREUSED ErrorCode = "IDEMPOTENCY_KEY_REUSED"
	INTERNALERROR        ErrorCode = "INTERNAL_ERROR"
	UNAUTHORIZEDSERVICE  ErrorCode = "UNAUTHORIZED_SERVICE"
	VALIDATIONERROR      ErrorCode = "VALIDATION_ERROR"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case AUTHORITYTIMEOUT:
		return true
	case IDEMPOTENCYKEYREUSED:
		return true
	case INTERNALERROR:
		return true
	case UNAUTHORIZEDSERVICE:
		return true
	case VALIDATIONERROR:
		return true
	default:
		return false
	}
}

// Defines values for FiscalRequestAssociatedVoucherDocumentType.
const (
	FiscalRequestAssociatedVoucherDocumentTypeFA FiscalRequestAssociatedVoucherDocumentType = "FA"
	FiscalRequestAssociatedVoucherDocumentTypeFB FiscalRequestAssociatedVoucherDocumentType = "FB"
	FiscalRequestAssociatedVoucherDocumentTypeFC FiscalRequestAssociatedVoucherDocumentType = "FC"
)

// Valid indicates whether the value is a known member of the FiscalRequestAssociatedVoucherDocumentType enum.
func (e FiscalRequestAssociatedVoucherDocumentType) Valid() bool {
	switch e {
	case FiscalRequestAssociatedVoucherDocumentTypeFA:
		return true
	case FiscalRequestAssociatedVoucherDocumentTypeFB:
		return true
	case FiscalRequestAssociatedVoucherDocumentTypeFC:
		return true
	default:
		return false
	}
}

// Defines values for FiscalRequestCurrency.
const (
	ARS FiscalRequestCurrency = "ARS"
	EUR FiscalRequestCurrency = "EUR"
	USD FiscalRequestCurrency = "USD"
)

// Valid indicates whether the value is a known member of the FiscalRequestCurrency enum.
func (e FiscalRequestCurrency) Valid() bool {
	switch e {
	case ARS:
		return true
	case EUR:
		return true
	case USD:
		return true
	default:
		return false
	}
}

// Defines values for FiscalRequestDocumentType.
const (
	FiscalRequestDocumentTypeFA  FiscalRequestDocumentType = "FA"
	FiscalRequestDocumentTypeFB  FiscalRequestDocumentType = "FB"
	FiscalRequestDocumentTypeFC  FiscalRequestDocumentType = "FC"
	FiscalRequestDocumentTypeNCA FiscalRequestDocumentType = "NCA"
	FiscalRequestDocumentTypeNCB FiscalRequestDocumentType = "NCB"
	FiscalRequestDocumentTypeNCC FiscalRequestDocumentType = "NCC"
	FiscalRequestDocumentTypeNDA FiscalRequestDocumentType = "NDA"
	FiscalRequestDocumentTypeNDB FiscalRequestDocumentType = "NDB"
	FiscalRequestDocumentTypeNDC FiscalRequestDocumentType = "NDC"
)

// Valid indicates whether the value is a known member of the FiscalRequestDocumentType enum.
func (e FiscalRequestDocumentType) Valid() bool {
	switch e {
	case FiscalRequestDocumentTypeFA:
		return true
	case FiscalRequestDocumentTypeFB:
		return true
	case FiscalRequestDocumentTypeFC:
		return true
	case FiscalRequestDocumentTypeNCA:
		return true
	case FiscalRequestDocumentTypeNCB:
		return true
	case FiscalRequestDocumentTypeNCC:
		return true
	case FiscalRequestDocumentTypeNDA:
		return true
	case FiscalRequestDocumentTypeNDB:
		return true
	case FiscalRequestDocumentTypeNDC:
		return true
	default:
		return false
	}
}

// Defines values for FiscalRequestEnvironment.
const (
	Homologation FiscalRequestEnvironment = "homologation"
	Production   FiscalRequestEnvironment = "production"
)

// Valid indicates whether the value is a known member of the FiscalRequestEnvironment enum.
func (e FiscalRequestEnvironment) Valid() bool {
	switch e {
	case Homologation:
		return true
	case Production:
		return true
	default:
		return false
	}
}

// Defines values for FiscalResultStatus.
const (
	Authorized FiscalResultStatus = "authorized"
	NotFound   FiscalResultStatus = "not_found"
	Rejected   FiscalResultStatus = "rejected"
	Uncertain  FiscalResultStatus = "uncertain"
)

// Valid indicates whether the value is a known member of the FiscalResultStatus enum.
func (e FiscalResultStatus) Valid() bool {
	switch e {
	case Authorized:
		return true
	case NotFound:
		return true
	case Rejected:
		return true
	case Uncertain:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	Ok HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MetricsUnavailableCode.
const (
	METRICSUNAVAILABLE MetricsUnavailableCode = "METRICS_UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the MetricsUnavailableCode enum.
func (e MetricsUnavailableCode) Valid() bool {
	switch e {
	case METRICSUNAVAILABLE:
		return true
	default:
		return false
	}
}

// Defines values for NotReadyStatusStatus.
const (
	NotReady NotReadyStatusStatus = "not_ready"
)

// Valid indicates whether the value is a known member of the NotReadyStatusStatus enum.
func (e NotReadyStatusStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatusStatus.
const (
	Ready ReadinessStatusStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessStatusStatus enum.
func (e ReadinessStatusStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for ListDocumentTypes200JSONResponseBodyCode.
const (
	ListDocumentTypes200JSONResponseBodyCodeFA  ListDocumentTypes200JSONResponseBodyCode = "FA"
	ListDocumentTypes200JSONResponseBodyCodeFB  ListDocumentTypes200JSONResponseBodyCode = "FB"
	ListDocumentTypes200JSONResponseBodyCodeFC  ListDocumentTypes200JSONResponseBodyCode = "FC"
	ListDocumentTypes200JSONResponseBodyCodeNCA ListDocumentTypes200JSONResponseBodyCode = "NCA"
	ListDocumentTypes200JSONResponseBodyCodeNCB ListDocumentTypes200JSONResponseBodyCode = "NCB"
	ListDocumentTypes200JSONResponseBodyCodeNCC ListDocumentTypes200JSONResponseBodyCode = "NCC"
	ListDocumentTypes200JSONResponseBodyCodeNDA ListDocumentTypes200JSONResponseBodyCode = "NDA"
	ListDocumentTypes200JSONResponseBodyCodeNDB ListDocumentTypes200JSONResponseBodyCode = "NDB"
	ListDocumentTypes200JSONResponseBodyCodeNDC ListDocumentTypes200JSONResponseBodyCode = "NDC"
)

// Valid indicates whether the value is a known member of the ListDocumentTypes200JSONResponseBodyCode enum.
func (e ListDocumentTypes200JSONResponseBodyCode) Valid() bool {
	switch e {
	case ListDocumentTypes200JSONResponseBodyCodeFA:
		return true
	case ListDocumentTypes200JSONResponseBodyCodeFB:
		return true
	case ListDocumentTypes200JSONResponseBodyCodeFC:
		return true
	case ListDocumentTypes200JSONResponseBodyCodeNCA:
		return true
	case ListDocumentTypes200JSONResponseBodyCodeNCB:
		return true
	case ListDocumentTypes200JSONResponseBodyCodeNCC:
		return true
	case ListDocumentTypes200JSONResponseBodyCodeNDA:
		return true
	case ListDocumentTypes200JSONResponseBodyCodeNDB:
		return true
	case ListDocumentTypes200JSONResponseBodyCodeNDC:
		return true
	default:
		return false
	}
}

// Defines values for ListDocumentTypes200JSONResponseBodyKind.
const (
	CreditNote ListDocumentTypes200JSONResponseBodyKind = "credit_note"
	DebitNote  ListDocumentTypes200JSONResponseBodyKind = "debit_note"
	Invoice    ListDocumentTypes200JSONResponseBodyKind = "invoice"
)

// Valid indicates whether the value is a known member of the ListDocumentTypes200JSONResponseBodyKind enum.
func (e ListDocumentTypes200JSONResponseBodyKind) Valid() bool {
	switch e {
	case CreditNote:
		return true
	case DebitNote:
		return true
	case Invoice:
		return true
	default:
		return false
	}
}

// Defines values for ListDocumentTypes200JSONResponseBodyLetter.
const (
	A ListDocumentTypes200JSONResponseBodyLetter = "A"
	B ListDocumentTypes200JSONResponseBodyLetter = "B"
	C ListDocumentTypes200JSONResponseBodyLetter = "C"
)

// Valid indicates whether the value is a known member of the ListDocumentTypes200JSONResponseBodyLetter enum.
func (e ListDocumentTypes200JSONResponseBodyLetter) Valid() bool {
	switch e {
	case A:
		return true
	case B:
		return true
	case C:
		return true
	default:
		return false
	}
}

// Decimal Decimal base diez exacto, sin signo, exponente ni JSON number.
type Decimal = string

// Error defines model for Error.
type Error struct {
	Code          ErrorCode `json:"code"`
	CorrelationId string    `json:"correlation_id"`
	Detail        *string   `json:"detail,omitempty"`
	Title         string    `json:"title"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// FiscalRequest idempotency_key y correlation_id deben coincidir con sus headers. source_version identifica la versión del documento Pymes y snapshot_digest su hash SHA-256 inmutable.
type FiscalRequest struct {
	AssociatedVoucher *struct {
		DocumentType  FiscalRequestAssociatedVoucherDocumentType `json:"document_type"`
		IssueDate     openapi_types.Date                         `json:"issue_date"`
		PointOfSale   int                                        `json:"point_of_sale"`
		VoucherNumber int                                        `json:"voucher_number"`
	} `json:"associated_voucher,omitempty"`
	CorrelationId string `json:"correlation_id"`

	// CredentialRef Referencia KMS/secret; jamás certificado o clave.
	CredentialRef string                    `json:"credential_ref"`
	Currency      FiscalRequestCurrency     `json:"currency"`
	DocumentType  FiscalRequestDocumentType `json:"document_type"`
	Environment   FiscalRequestEnvironment  `json:"environment"`

	// ExchangeRate Obligatorio para USD y EUR.
	ExchangeRate   *PositiveDecimal   `json:"exchange_rate,omitempty"`
	IdempotencyKey string             `json:"idempotency_key"`
	IssueDate      openapi_types.Date `json:"issue_date"`
	Lines          []struct {
		Description string `json:"description"`

		// Net Decimal base diez exacto, sin signo, exponente ni JSON number.
		Net Decimal `json:"net"`

		// Quantity Decimal base diez exacto estrictamente mayor que cero.
		Quantity PositiveDecimal `json:"quantity"`

		// UnitPrice Decimal base diez exacto, sin signo, exponente ni JSON number.
		UnitPrice Decimal `json:"unit_price"`

		// VatRate Alícuota IVA soportada por el mock (0; 2,5; 5; 10,5; 21 o 27).
		VatRate VatRate `json:"vat_rate"`
	} `json:"lines"`
	OrganizationId string `json:"organization_id"`
	PointOfSale    int    `json:"point_of_sale"`
	Recipient      struct {
		DocumentNumber string `json:"document_number"`
		DocumentType   string `json:"document_type"`
		VatCondition   string `json:"vat_condition"`
	} `json:"recipient"`
	RequestId string `json:"request_id"`

	// SnapshotDigest Hash SHA-256 hexadecimal del documento congelado.
	SnapshotDigest string `json:"snapshot_digest"`
	SourceVersion  int    `json:"source_version"`
	Totals         struct {
		// Exempt Decimal base diez exacto, sin signo, exponente ni JSON number.
		Exempt Decimal `json:"exempt"`

		// Net Decimal base diez exacto, sin signo, exponente ni JSON number.
		Net Decimal `json:"net"`

		// Total Decimal base diez exacto, sin signo, exponente ni JSON number.
		Total Decimal `json:"total"`

		// Vat Decimal base diez exacto, sin signo, exponente ni JSON number.
		Vat Decimal `json:"vat"`
	} `json:"totals"`

	// VoucherNumber Reservado por Pymes.
	VoucherNumber int `json:"voucher_number"`
}

// FiscalRequestAssociatedVoucherDocumentType defines model for FiscalRequest.AssociatedVoucher.DocumentType.
type FiscalRequestAssociatedVoucherDocumentType string

// FiscalRequestCurrency defines model for FiscalRequest.Currency.
type FiscalRequestCurrency string

// FiscalRequestDocumentType defines model for FiscalRequest.DocumentType.
type FiscalRequestDocumentType string

// FiscalRequestEnvironment defines model for FiscalRequest.Environment.
type FiscalRequestEnvironment string

// FiscalResult defines model for FiscalResult.
type FiscalResult struct {
	// ArtifactRef Referencia privada al XML cifrado
	ArtifactRef         *string             `json:"artifact_ref,omitempty"`
	AuthorityMessages   *[]string           `json:"authority_messages,omitempty"`
	AuthorityResultCode *string             `json:"authority_result_code,omitempty"`
	Cae                 *string             `json:"cae,omitempty"`
	CaeExpiresOn        *openapi_types.Date `json:"cae_expires_on,omitempty"`
	CorrelationId       string              `json:"correlation_id"`
	IdempotencyKey      string              `json:"idempotency_key"`
	ObservedAt          time.Time           `json:"observed_at"`
	OrganizationId      string              `json:"organization_id"`
	RequestId           string              `json:"request_id"`
	SnapshotDigest      string              `json:"snapshot_digest"`
	SourceVersion       int                 `json:"source_version"`
	Status              FiscalResultStatus  `json:"status"`
}

// FiscalResultStatus defines model for FiscalResult.Status.
type FiscalResultStatus string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// MetricsUnavailable defines model for MetricsUnavailable.
type MetricsUnavailable struct {
	Code MetricsUnavailableCode `json:"code"`
}

// MetricsUnavailableCode defines model for MetricsUnavailable.Code.
type MetricsUnavailableCode string

// NotReadyStatus defines model for NotReadyStatus.
type NotReadyStatus struct {
	Status NotReadyStatusStatus `json:"status"`
}

// NotReadyStatusStatus defines model for NotReadyStatus.Status.
type NotReadyStatusStatus string

// PositiveDecimal Decimal base diez exacto estrictamente mayor que cero.
type PositiveDecimal = string

// ReadinessStatus defines model for ReadinessStatus.
type ReadinessStatus struct {
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string

// VatRate Alícuota IVA soportada por el mock (0; 2,5; 5; 10,5; 21 o 27).
type VatRate = string

// CorrelationId defines model for CorrelationId.
type CorrelationId = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// OrganizationId defines model for OrganizationId.
type OrganizationId = string

// AuthorityUnavailable defines model for AuthorityUnavailable.
type AuthorityUnavailable = Error

// Conflict defines model for Conflict.
type Conflict = Error

// DomainError defines model for DomainError.
type DomainError = Error

// InternalError defines model for InternalError.
type InternalError = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListDocumentTypesParams defines parameters for ListDocumentTypes.
type ListDocumentTypesParams struct {
	// XCorrelationID Identificador estable propagado de extremo a extremo.
	XCorrelationID CorrelationId `json:"X-Correlation-ID"`
}

// ListDocumentTypes200JSONResponseBodyCode defines parameters for ListDocumentTypes.
type ListDocumentTypes200JSONResponseBodyCode string

// ListDocumentTypes200JSONResponseBodyKind defines parameters for ListDocumentTypes.
type ListDocumentTypes200JSONResponseBodyKind string

// ListDocumentTypes200JSONResponseBodyLetter defines parameters for ListDocumentTypes.
type ListDocumentTypes200JSONResponseBodyLetter string

// RequestAuthorizationParams defines parameters for RequestAuthorization.
type RequestAuthorizationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// XCorrelationID Identificador estable propagado de extremo a extremo.
	XCorrelationID CorrelationId `json:"X-Correlation-ID"`
}

// ConsultAuthorizationParams defines parameters for ConsultAuthorization.
type ConsultAuthorizationParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`

	// XCorrelationID Identificador estable propagado de extremo a extremo.
	XCorrelationID CorrelationId `json:"X-Correlation-ID"`
}

// RequestAuthorizationJSONRequestBody defines body for RequestAuthorization for application/json ContentType.
type RequestAuthorizationJSONRequestBody = FiscalRequest

// ConsultAuthorizationJSONRequestBody defines body for ConsultAuthorization for application/json ContentType.
type ConsultAuthorizationJSONRequestBody = FiscalRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// FiscalHealth performs a GET /healthz (the `FiscalHealth` operationId) request.
	FiscalHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDocumentTypes performs a GET /internal/v1/catalogs/document-types (the `ListDocumentTypes` operationId) request.
	ListDocumentTypes(ctx context.Context, params *ListDocumentTypesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RequestAuthorizationWithBody performs a POST /internal/v1/organizations/{organizationId}/authorizations (the `RequestAuthorization` operationId) request,
	// with any type of body and a specified content type.
	RequestAuthorizationWithBody(ctx context.Context, organizationId OrganizationId, params *RequestAuthorizationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RequestAuthorization performs a POST /internal/v1/organizations/{organizationId}/authorizations (the `RequestAuthorization` operationId) request.
	// Takes a body of the `application/json` content type.
	RequestAuthorization(ctx context.Context, organizationId OrganizationId, params *RequestAuthorizationParams, body RequestAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConsultAuthorizationWithBody performs a POST /internal/v1/organizations/{organizationId}/authorizations/{requestId}/consult (the `ConsultAuthorization` operationId) request,
	// with any type of body and a specified content type.
	ConsultAuthorizationWithBody(ctx context.Context, organizationId OrganizationId, requestId string, params *ConsultAuthorizationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConsultAuthorization performs a POST /internal/v1/organizations/{organizationId}/authorizations/{requestId}/consult (the `ConsultAuthorization` operationId) request.
	// Takes a body of the `application/json` content type.
	ConsultAuthorization(ctx context.Context, organizationId OrganizationId, requestId string, params *ConsultAuthorizationParams, body ConsultAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FiscalMetrics performs a GET /metrics (the `FiscalMetrics` operationId) request.
	FiscalMetrics(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FiscalReadiness performs a GET /readyz (the `FiscalReadiness` operationId) request.
	FiscalReadiness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// FiscalHealth performs a GET /healthz (the `FiscalHealth` operationId) request.
func (c *Client) FiscalHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFiscalHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListDocumentTypes performs a GET /internal/v1/catalogs/document-types (the `ListDocumentTypes` operationId) request.
func (c *Client) ListDocumentTypes(ctx context.Context, params *ListDocumentTypesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDocumentTypesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RequestAuthorizationWithBody performs a POST /internal/v1/organizations/{organizationId}/authorizations (the `RequestAuthorization` operationId) request,
// with any type of body and a specified content type.
func (c *Client) RequestAuthorizationWithBody(ctx context.Context, organizationId OrganizationId, params *RequestAuthorizationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRequestAuthorizationRequestWithBody(c.Server, organizationId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RequestAuthorization performs a POST /internal/v1/organizations/{organizationId}/authorizations (the `RequestAuthorization` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) RequestAuthorization(ctx context.Context, organizationId OrganizationId, params *RequestAuthorizationParams, body RequestAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRequestAuthorizationRequest(c.Server, organizationId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ConsultAuthorizationWithBody performs a POST /internal/v1/organizations/{organizationId}/authorizations/{requestId}/consult (the `ConsultAuthorization` operationId) request,
// with any type of body and a specified content type.
func (c *Client) ConsultAuthorizationWithBody(ctx context.Context, organizationId OrganizationId, requestId string, params *ConsultAuthorizationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConsultAuthorizationRequestWithBody(c.Server, organizationId, requestId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ConsultAuthorization performs a POST /internal/v1/organizations/{organizationId}/authorizations/{requestId}/consult (the `ConsultAuthorization` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) ConsultAuthorization(ctx context.Context, organizationId OrganizationId, requestId string, params *ConsultAuthorizationParams, body ConsultAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConsultAuthorizationRequest(c.Server, organizationId, requestId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// FiscalMetrics performs a GET /metrics (the `FiscalMetrics` operationId) request.
func (c *Client) FiscalMetrics(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFiscalMetricsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// FiscalReadiness performs a GET /readyz (the `FiscalReadiness` operationId) request.
func (c *Client) FiscalReadiness(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFiscalReadinessRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewFiscalHealthRequest constructs an http.Request for the FiscalHealth method
func NewFiscalHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDocumentTypesRequest constructs an http.Request for the ListDocumentTypes method
func NewListDocumentTypesRequest(server string, params *ListDocumentTypesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/catalogs/document-types")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Correlation-ID", params.XCorrelationID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Correlation-ID", headerParam0)

	}

	return req, nil
}

// NewRequestAuthorizationRequest calls the generic RequestAuthorization builder with application/json body
func NewRequestAuthorizationRequest(server string, organizationId OrganizationId, params *RequestAuthorizationParams, body RequestAuthorizationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRequestAuthorizationRequestWithBody(server, organizationId, params, "application/json", bodyReader)
}

// NewRequestAuthorizationRequestWithBody constructs an http.Request for the RequestAuthorization method, with any body, and a specified content type
func NewRequestAuthorizationRequestWithBody(server string, organizationId OrganizationId, params *RequestAuthorizationParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organizationId", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/organizations/%s/authorizations", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Correlation-ID", params.XCorrelationID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Correlation-ID", headerParam1)

	}

	return req, nil
}

// NewConsultAuthorizationRequest calls the generic ConsultAuthorization builder with application/json body
func NewConsultAuthorizationRequest(server string, organizationId OrganizationId, requestId string, params *ConsultAuthorizationParams, body ConsultAuthorizationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewConsultAuthorizationRequestWithBody(server, organizationId, requestId, params, "application/json", bodyReader)
}

// NewConsultAuthorizationRequestWithBody constructs an http.Request for the ConsultAuthorization method, with any body, and a specified content type
func NewConsultAuthorizationRequestWithBody(server string, organizationId OrganizationId, requestId string, params *ConsultAuthorizationParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organizationId", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "requestId", requestId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/organizations/%s/authorizations/%s/consult", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "X-Correlation-ID", params.XCorrelationID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Correlation-ID", headerParam1)

	}

	return req, nil
}

// NewFiscalMetricsRequest constructs an http.Request for the FiscalMetrics method
func NewFiscalMetricsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/metrics")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFiscalReadinessRequest constructs an http.Request for the FiscalReadiness method
func NewFiscalReadinessRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// FiscalHealthWithResponse performs a GET /healthz (the `FiscalHealth` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	FiscalHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FiscalHealthResponse, error)

	// ListDocumentTypesWithResponse performs a GET /internal/v1/catalogs/document-types (the `ListDocumentTypes` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	ListDocumentTypesWithResponse(ctx context.Context, params *ListDocumentTypesParams, reqEditors ...RequestEditorFn) (*ListDocumentTypesResponse, error)

	// RequestAuthorizationWithBodyWithResponse performs a POST /internal/v1/organizations/{organizationId}/authorizations (the `RequestAuthorization` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	RequestAuthorizationWithBodyWithResponse(ctx context.Context, organizationId OrganizationId, params *RequestAuthorizationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RequestAuthorizationResponse, error)

	// RequestAuthorizationWithResponse performs a POST /internal/v1/organizations/{organizationId}/authorizations (the `RequestAuthorization` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	RequestAuthorizationWithResponse(ctx context.Context, organizationId OrganizationId, params *RequestAuthorizationParams, body RequestAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*RequestAuthorizationResponse, error)

	// ConsultAuthorizationWithBodyWithResponse performs a POST /internal/v1/organizations/{organizationId}/authorizations/{requestId}/consult (the `ConsultAuthorization` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	ConsultAuthorizationWithBodyWithResponse(ctx context.Context, organizationId OrganizationId, requestId string, params *ConsultAuthorizationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConsultAuthorizationResponse, error)

	// ConsultAuthorizationWithResponse performs a POST /internal/v1/organizations/{organizationId}/authorizations/{requestId}/consult (the `ConsultAuthorization` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	ConsultAuthorizationWithResponse(ctx context.Context, organizationId OrganizationId, requestId string, params *ConsultAuthorizationParams, body ConsultAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*ConsultAuthorizationResponse, error)

	// FiscalMetricsWithResponse performs a GET /metrics (the `FiscalMetrics` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	FiscalMetricsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FiscalMetricsResponse, error)

	// FiscalReadinessWithResponse performs a GET /readyz (the `FiscalReadiness` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	FiscalReadinessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FiscalReadinessResponse, error)
}

type FiscalHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *HealthStatus
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r FiscalHealthResponse) GetJSON200() *HealthStatus {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r FiscalHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FiscalHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FiscalHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FiscalHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListDocumentTypesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]struct {
		Code   ListDocumentTypes200JSONResponseBodyCode   `json:"code"`
		Kind   ListDocumentTypes200JSONResponseBodyKind   `json:"kind"`
		Letter ListDocumentTypes200JSONResponseBodyLetter `json:"letter"`
	}
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *DomainError
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *InternalError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDocumentTypesResponse) GetJSON200() *[]struct {
	Code   ListDocumentTypes200JSONResponseBodyCode   `json:"code"`
	Kind   ListDocumentTypes200JSONResponseBodyKind   `json:"kind"`
	Letter ListDocumentTypes200JSONResponseBodyLetter `json:"letter"`
} {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r ListDocumentTypesResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r ListDocumentTypesResponse) GetApplicationproblemJSON422() *DomainError {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r ListDocumentTypesResponse) GetApplicationproblemJSON500() *InternalError {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r ListDocumentTypesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDocumentTypesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDocumentTypesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDocumentTypesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RequestAuthorizationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *FiscalResult
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *FiscalResult
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON409 the response for an HTTP 409 `application/problem+json` response
	ApplicationproblemJSON409 *Conflict
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *DomainError
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *InternalError
	// ApplicationproblemJSON503 the response for an HTTP 503 `application/problem+json` response
	ApplicationproblemJSON503 *AuthorityUnavailable
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r RequestAuthorizationResponse) GetJSON201() *FiscalResult {
	return r.JSON201
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r RequestAuthorizationResponse) GetJSON202() *FiscalResult {
	return r.JSON202
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r RequestAuthorizationResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON409 returns the response for an HTTP 409 `application/problem+json` response
func (r RequestAuthorizationResponse) GetApplicationproblemJSON409() *Conflict {
	return r.ApplicationproblemJSON409
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r RequestAuthorizationResponse) GetApplicationproblemJSON422() *DomainError {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r RequestAuthorizationResponse) GetApplicationproblemJSON500() *InternalError {
	return r.ApplicationproblemJSON500
}

// GetApplicationproblemJSON503 returns the response for an HTTP 503 `application/problem+json` response
func (r RequestAuthorizationResponse) GetApplicationproblemJSON503() *AuthorityUnavailable {
	return r.ApplicationproblemJSON503
}

// GetBody returns the raw response body bytes
func (r RequestAuthorizationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RequestAuthorizationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RequestAuthorizationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RequestAuthorizationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ConsultAuthorizationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *FiscalResult
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Unauthorized
	// ApplicationproblemJSON409 the response for an HTTP 409 `application/problem+json` response
	ApplicationproblemJSON409 *Conflict
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *DomainError
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *InternalError
	// ApplicationproblemJSON503 the response for an HTTP 503 `application/problem+json` response
	ApplicationproblemJSON503 *AuthorityUnavailable
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ConsultAuthorizationResponse) GetJSON200() *FiscalResult {
	return r.JSON200
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r ConsultAuthorizationResponse) GetApplicationproblemJSON401() *Unauthorized {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON409 returns the response for an HTTP 409 `application/problem+json` response
func (r ConsultAuthorizationResponse) GetApplicationproblemJSON409() *Conflict {
	return r.ApplicationproblemJSON409
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r ConsultAuthorizationResponse) GetApplicationproblemJSON422() *DomainError {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r ConsultAuthorizationResponse) GetApplicationproblemJSON500() *InternalError {
	return r.ApplicationproblemJSON500
}

// GetApplicationproblemJSON503 returns the response for an HTTP 503 `application/problem+json` response
func (r ConsultAuthorizationResponse) GetApplicationproblemJSON503() *AuthorityUnavailable {
	return r.ApplicationproblemJSON503
}

// GetBody returns the raw response body bytes
func (r ConsultAuthorizationResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ConsultAuthorizationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConsultAuthorizationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ConsultAuthorizationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FiscalMetricsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *MetricsUnavailable
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r FiscalMetricsResponse) GetJSON503() *MetricsUnavailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r FiscalMetricsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FiscalMetricsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FiscalMetricsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FiscalMetricsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FiscalReadinessResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ReadinessStatus
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *NotReadyStatus
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r FiscalReadinessResponse) GetJSON200() *ReadinessStatus {
	return r.JSON200
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r FiscalReadinessResponse) GetJSON503() *NotReadyStatus {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r FiscalReadinessResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r FiscalReadinessResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FiscalReadinessResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FiscalReadinessResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// FiscalHealthWithResponse performs a GET /healthz (the `FiscalHealth` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) FiscalHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FiscalHealthResponse, error) {
	rsp, err := c.FiscalHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFiscalHealthResponse(rsp)
}

// ListDocumentTypesWithResponse performs a GET /internal/v1/catalogs/document-types (the `ListDocumentTypes` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ListDocumentTypesWithResponse(ctx context.Context, params *ListDocumentTypesParams, reqEditors ...RequestEditorFn) (*ListDocumentTypesResponse, error) {
	rsp, err := c.ListDocumentTypes(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDocumentTypesResponse(rsp)
}

// RequestAuthorizationWithBodyWithResponse performs a POST /internal/v1/organizations/{organizationId}/authorizations (the `RequestAuthorization` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) RequestAuthorizationWithBodyWithResponse(ctx context.Context, organizationId OrganizationId, params *RequestAuthorizationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RequestAuthorizationResponse, error) {
	rsp, err := c.RequestAuthorizationWithBody(ctx, organizationId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRequestAuthorizationResponse(rsp)
}

// RequestAuthorizationWithResponse performs a POST /internal/v1/organizations/{organizationId}/authorizations (the `RequestAuthorization` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) RequestAuthorizationWithResponse(ctx context.Context, organizationId OrganizationId, params *RequestAuthorizationParams, body RequestAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*RequestAuthorizationResponse, error) {
	rsp, err := c.RequestAuthorization(ctx, organizationId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRequestAuthorizationResponse(rsp)
}

// ConsultAuthorizationWithBodyWithResponse performs a POST /internal/v1/organizations/{organizationId}/authorizations/{requestId}/consult (the `ConsultAuthorization` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ConsultAuthorizationWithBodyWithResponse(ctx context.Context, organizationId OrganizationId, requestId string, params *ConsultAuthorizationParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ConsultAuthorizationResponse, error) {
	rsp, err := c.ConsultAuthorizationWithBody(ctx, organizationId, requestId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConsultAuthorizationResponse(rsp)
}

// ConsultAuthorizationWithResponse performs a POST /internal/v1/organizations/{organizationId}/authorizations/{requestId}/consult (the `ConsultAuthorization` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ConsultAuthorizationWithResponse(ctx context.Context, organizationId OrganizationId, requestId string, params *ConsultAuthorizationParams, body ConsultAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*ConsultAuthorizationResponse, error) {
	rsp, err := c.ConsultAuthorization(ctx, organizationId, requestId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConsultAuthorizationResponse(rsp)
}

// FiscalMetricsWithResponse performs a GET /metrics (the `FiscalMetrics` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) FiscalMetricsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FiscalMetricsResponse, error) {
	rsp, err := c.FiscalMetrics(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFiscalMetricsResponse(rsp)
}

// FiscalReadinessWithResponse performs a GET /readyz (the `FiscalReadiness` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) FiscalReadinessWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*FiscalReadinessResponse, error) {
	rsp, err := c.FiscalReadiness(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFiscalReadinessResponse(rsp)
}

// ParseFiscalHealthResponse parses an HTTP response from a FiscalHealthWithResponse call
func ParseFiscalHealthResponse(rsp *http.Response) (*FiscalHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FiscalHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListDocumentTypesResponse parses an HTTP response from a ListDocumentTypesWithResponse call
func ParseListDocumentTypesResponse(rsp *http.Response) (*ListDocumentTypesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDocumentTypesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct {
			Code   ListDocumentTypes200JSONResponseBodyCode   `json:"code"`
			Kind   ListDocumentTypes200JSONResponseBodyKind   `json:"kind"`
			Letter ListDocumentTypes200JSONResponseBodyLetter `json:"letter"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest DomainError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseRequestAuthorizationResponse parses an HTTP response from a RequestAuthorizationWithResponse call
func ParseRequestAuthorizationResponse(rsp *http.Response) (*RequestAuthorizationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RequestAuthorizationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest FiscalResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest FiscalResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest DomainError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest AuthorityUnavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON503 = &dest

	}

	return response, nil
}

// ParseConsultAuthorizationResponse parses an HTTP response from a ConsultAuthorizationWithResponse call
func ParseConsultAuthorizationResponse(rsp *http.Response) (*ConsultAuthorizationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConsultAuthorizationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FiscalResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest DomainError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest AuthorityUnavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON503 = &dest

	}

	return response, nil
}

// ParseFiscalMetricsResponse parses an HTTP response from a FiscalMetricsWithResponse call
func ParseFiscalMetricsResponse(rsp *http.Response) (*FiscalMetricsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FiscalMetricsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest MetricsUnavailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseFiscalReadinessResponse parses an HTTP response from a FiscalReadinessWithResponse call
func ParseFiscalReadinessResponse(rsp *http.Response) (*FiscalReadinessResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FiscalReadinessResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReadinessStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest NotReadyStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
